### ISSUE TITLE
Document Uninstall for Telemetry Dashboard v3 and lower.

### ISSUE THREAD

**Issue by jparis** [eapowertools/qs-telemetry-dashboard#17]

**Comment by VictorBosch** [comment]
There is any documentation regarding uninstall/update Telemetry dashboard?
Thank you

**Comment by jparis** [comment]
What version?

**Comment by VictorBosch** [comment]
Telemetry Dashboard 4.2.2.

**Comment by jparis** [comment]
If you want to remove it, just delete the Telemetry Dashboard folder with all the files in it, and remove the tasks. There are no temp files or keys installed, it's simply just the .exe.

**Comment by VictorBosch** [comment]
Thank you

În lun., 7 iun. 2021 la 18:53, Jesse Paris ***@***.***> a
scris:

**Comment by jparis** [comment]
Finally done this:

https://github.com/eapowertools-archive/qs-telemetry-dashboard-node/wiki/Upgrade-Uninstall

closing!
