### ISSUE TITLE
Schedule TelemetryDashboard-1-Generate-Metadata

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-telemetry-dashboard#18]
See above

In the interim, see: 
 - https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata (Qlik-Cli-Windows)
 - https://gist.github.com/levi-turner/f4a431b306c399c7c5caf0406a0a8be9 (Raw PowerShell)

**Comment by jparis** [comment]
This was released in May 2021, closing this as functionality now exists natively.
