### ISSUE TITLE
systemInfo TotalMemory values in multinode deployment

### ISSUE THREAD

**Issue by gorkor** [eapowertools/qs-telemetry-dashboard#19]
Hi!
The file systemInfo.csv only contains one record for key "TotalMemory(GB)" even in a multinode deployment. (for node "localhost")
It would be great to have this by node in the cluster (like for the "Working Set" values).

**Comment by levi-turner** [comment]
`systemInfo.csv` will not contain memory in the refactored Telemetry 4.0 which should GA very soon.

**Comment by gorkor** [comment]
OK, looking forward to the new version!
