### ISSUE TITLE
Corrupt Sheets will stop metafetch for the remainder of sheets for an app.

### ISSUE THREAD

**Issue by jparis** [eapowertools/qs-telemetry-dashboard#22]
When the engine app metadata fetch fails, the whole app stops fetching data even if there is good data that follows. fix this!

**Comment by qlik-peterman** [comment]
Damn...”Fix this!”  ???

How about....”thank you for doing what your product team would not do, enabling me with this free power tool.”

On Aug 7, 2018, at 1:34 PM, Jesse Paris <notifications@github.com<mailto:notifications@github.com>> wrote:


When the engine app metadata fetch fails, the whole app stops fetching data even if there is good data that follows. fix this!

**Comment by jparis** [comment]
No longer an issue as we don't dive deep into sheets. closing this.
