### ISSUE TITLE
Log date filter hard coded to US format

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#23]
I changed the variables in the Main section to have UK format dates / times etc.

However when I did this, no log files were picked up.
I traced it down to the line that sets the value of vDaysSinceTelemetryRelease:
`LET vDaysSinceTelemetryRelease = Ceil(Now() - Date('13/02/2018'));`

I changed this to UK format and the app reloaded with data fine:
`LET vDaysSinceTelemetryRelease = Ceil(Now() - Date('02/13/2018'));`

And then this to make it more generic:
`LET vDaysSinceTelemetryRelease = Ceil(Now() - MakeDate(2018,2,13));`

And it also reloaded fine.

**Comment by levi-turner** [comment]
Fixed in https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/v4.0.1
