### ISSUE TITLE
All Deleted Apps get the same name so are grouped together.

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#24]
We have quite a few deleted apps in our environment, so the "Deleted App" for "AppName" in the "Visualization Drill" Master Dimension isn't that useful as it makes it look like there's one giant app outweighing everything else. 

I tweaked a line in the script to make the App Name unique at least from:
`    if(IsNull([AppName]),'Deleted App',[AppName]) AS [AppName],`
to
`    if(IsNull([AppName]),'Deleted App (' & AppID & ')',[AppName]) AS [AppName],`

Obviously app names can also be duplicated within the same environment, so maybe there's a better way of identifying duplicates and making sure they get unique names? I think the App Analyzer does that but I haven't dug into the logic.

**Comment by levi-turner** [comment]
That's a fair compromise to include the `AppId` as well as `Deleted`. For the duplicate identification both the App Analyzer and this app are using the `Dual()` function to provide uniqueness:

```
[apps]:
LOAD 
	[AppID] AS [AppID],
    Dual([AppName],AutoNumber([AppID])) AS [AppName],
	[IsPublished],
	IF(LEN([StreamName])>0,[StreamName],'Unpublished') AS [StreamName];
LOAD [AppID],
	[AppName],
	[IsPublished],
	[PublishedDate],
	[StreamID],
	[StreamName]
FROM '[$(vTelemetryConnect)/apps.csv]' (txt, utf8, embedded labels, delimiter is '`');
```

**Comment by alexometis** [comment]
Actually It's already using the dual approach - it's just I had one Deleted App that was skewing the figures so much I assumed they'd all been bundled together (the reload showed as 500,000s but turns out it had just hung and only showed as ended when the Engine restarted).

**Comment by levi-turner** [comment]
Fixed in https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/v4.0.1
