### ISSUE TITLE
Non-Sheet objects get a Sheet Type

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#25]
Non-Sheet objects get a SheetType through this logic:
```
If([Published]='True' AND [Approved]='True','Base',
	If([Published]='True' AND [Approved]='False','Community',
		If([AppIsPublished]='True' AND [Published]='False','Private (Self-Service)','Private (Development)'))) AS [SheetType]
```

I've changed this to the following in my version and thought others might appreciate it too as it stops other things being flagged as 'Private (Development)'.
```
IF([SheetID]='N/A','N/A',
    	If([Published]='True' AND [Approved]='True','Base',
		If([Published]='True' AND [Approved]='False','Community',
			If([AppIsPublished]='True' AND [Published]='False','Private (Self-Service)','Private (Development)')))) AS [SheetType]
```

I guess another option would be to put the stream name or something else useful in there.

**Comment by levi-turner** [comment]
Fixed in https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/v4.0.1
