### ISSUE TITLE
MetaData Reload in Multinodes

### ISSUE THREAD

**Issue by Ersgersg** [eapowertools/qs-telemetry-dashboard#25]
Hi 

as we cannot force the task to be executed on the server where telemetry was installed in a multinodes environnment here is a hack : 
Copy the directory from the server where telemetry setup was run :
C:\Program Files\Qlik\Sense\EAPowerTools\TelemetryDashboard
into the same place on the others nodes

that will allow the task to run whatever nodes the task is executed.

be careful that output is generated in C:/ProgramData/Qlik/Sense/TelemetryMetadata/  on a single server

next step will be to update the config.js which is the directory 
c:\Program Files\Qlik\Sense\EAPowerTools\TelemetryDashboard\config

to change the outputDir: "C:/ProgramData/Qlik/Sense/TelemetryMetadata/",  to a shared directory : why not the QlikShare ??

**Comment by qlik-peterman** [comment]
the fix to the dashboard and installer for multi-node is being tested now.   it should be available very soon.
