### ISSUE TITLE
Archived Logs Not Loaded

### ISSUE THREAD

**Issue by Gutbuket** [eapowertools/qs-telemetry-dashboard#26]
In Sense June 2018 in a single node environment no Archived Loges were not loaded. The problem is that the vComputerName variable uses the ComputerName function, which doesn't return the FQDN (hostname.domain.something) which is the directory name for the archived log files.
e.g. \\share\Sense\ArchivedLogs\hostname.domain.somewhere

This worked after adding the domain to the vComputerName variable in the Main section: 
Let vComputerName = ComputerName() & '.domain.somewhere'; and reloading the App from the Script Editor.

The documentation and script notes need to be updated to add this a s a configuration item or change the way the script gets the directory names.

I couldn't find another way to get the FQDN in the script.

**Comment by jparis** [comment]
That's the right way to do it, will update the documentation then close then when I've done so. Thanks.
