### ISSUE TITLE
Task dependency not created

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#26]
After running the new exe as admin the tasks were created and app imported fine. The first task ran but didn't trigger the second. 

Looking at the Task list, it doesn't show a preceding task: ![image](https://user-images.githubusercontent.com/19587679/97879578-0ed20e80-1d18-11eb-870a-f6062369a62f.png)

When you click to edit it, it shows no task - and you're not able to select the first one - I think this is how it's always been since that's an "External program" Task Type not "Reload".
![image](https://user-images.githubusercontent.com/19587679/97879726-3c1ebc80-1d18-11eb-810b-b788fd819e37.png)

Note: this server has had various versions of Telemetry Dashboard on it before but I uninstalled them and deleted the old version of the App that was still on the server before running the exe.

**Comment by jparis** [comment]
found a bug. that's my bad.

fix is to delete the two tasks, and run the .exe again. 4.0.1 just got released which has a few app fixes, so i'd recommend that one. that'll solve the problem for now, and i'll work on a new version that fixes this issue.

**Comment by jparis** [comment]
fixed in v4.1.0
