### ISSUE TITLE
Unable to install msi package on QlikSense September 2018 Release

### ISSUE THREAD

**Issue by QS-Admin** [eapowertools/qs-telemetry-dashboard#27]
Installer is stopping with following error message
![image](https://user-images.githubusercontent.com/43431627/45797962-43092300-bca8-11e8-8396-e3c2df60e663.png)

This happens on 2 enviroments using QlikSense September 2018 Release.
If installing the package to a former release (February 2018), everythings is working fine.

**Comment by jparis** [comment]
Just tested this out... Works fine. Are you sure the QMC was accessible when running the installer?

**Comment by kiranrode07** [comment]
Qlik Sense telemetry dashboard Installation failing when the repository is installed on a remote host, not on the Qlik Sense server itself.

![capture](https://user-images.githubusercontent.com/39567496/46998999-c8d19e80-d180-11e8-8236-de839635797a.PNG)

**Comment by jparis** [comment]
Ah yes, needs to be installed on the central node. Will make sure to document that.

**Comment by levi-turner** [comment]
@kiranrode07  : Is the _Repository Service_ or is the _Repository Database_ on a remote host?

**Comment by kiranrode07** [comment]
@levi-turner :Both Repository service and database are on remote host.

**Comment by prashanthi-g** [comment]
Hi,
Im trying to install the telemetry but unable to as our naming convention in is different.
We saved the Qliksense Shared folder as qliksenseApps, QlkisenseArchivelogs as Apps, Archivelogs and so on. 
When I install its unable to find the App folder in the shared folder.

Can someone suggest me what i can do to get it installed correct.
I cannot change the naming conversion followed at my company
