### ISSUE TITLE
Only getting current day logs

### ISSUE THREAD

**Issue by pdwatt** [eapowertools/qs-telemetry-dashboard#31]
2 questions:
1/ How do you schedule this task to run automatically if you can't modify the first task?
2/ When I run it manually, it only shows activity from the current day. I'm trying to gauge changes to specific apps to see how they are performing over the past couple of weeks.

Thanks!

**Comment by jparis** [comment]
It should be pulling archived logs and non archived. If it's not pulling in old activity, you might not have access to the archived logs data connection.

As for running the first task automatically, you can edit it via the API to schedule it, but sadly given the bugs in the QMC, that's the only way to edit it at the moment.
