### ISSUE TITLE
Default bookmark to exclude Deleted Apps

### ISSUE THREAD

**Issue by rzenere-methode** [eapowertools/qs-telemetry-dashboard#31]
Good morning,

I would suggest to create a default bookmark that excludes the Deleted Apps.
On the field AppName, I would use the expression _=left(AppName, 11)<>'Deleted App'_ and then create the bookmark
Since (as far as I know) the expression is evaluated on each opening, it should be safe if a new app is deleted

Let me know what you think

Many thanks,
Riccardo

**Comment by levi-turner** [comment]
I am fine with that. As background, our approach to use of new functionality in the Telemetry Dashboard (and generally on all apps in the **eapowertools** grouping) is to wait for 2 years to pass. This means that all customers running a [supported](https://community.qlik.com/t5/Support-Knowledge-Base/Qlik-Sense-QlikView-NPrinting-End-of-Support-Date/ta-p/1711166) version of Qlik Sense Enterprise will have the functionality. I explored the use of using default bookmarks (introduced Sept 2018 aka the oldest supported version at the current time) and this is a good first offering in this area.

**Comment by rzenere-methode** [comment]
I believe we can close this issue, as the default bookmark has been implemented

Riccardo
