### ISSUE TITLE
v2.0.0 install fails with no error

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#32]
Just uninstalled v1.x and tried to install v2.0.0 but the install fails with no error and rolls back.

The network share in this case is on a different server but I can see the account running the installer has access to create files as it initially creates the TelemetryDashboard folder in there but then deletes it as part of the roll back. 

Not sure if it creates any log files that I can investigate - nothing that I could see in c:\Users\username\AppData\Local\Temp. Happy to help debug the issue if I can have some pointers.

**Comment by alexometis** [comment]
[TelemetryDashboard.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/2643262/TelemetryDashboard.log)

Looks like it's a permissions thing:

> MSI (s) (B0:B0) [09:41:42:788]: Executing op: ActionStart(Name=CreateFolders,Description=Creating folders,Template=Folder: [1])
> MSI (s) (B0:B0) [09:41:42:788]: Executing op: FolderCreate(Folder=\\omfs01\QlikSenseData\Development\TelemetryDashboard\MetadataGenerater\certs\,Foreign=0,SecurityDescriptor=BinaryData,)
> MSI (s) (B0:B0) [09:41:42:788]: Note: 1: 2205 2:  3: Error 
> MSI (s) (B0:B0) [09:41:42:788]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1926 
> Info 1926.Could not set file security for file '\\omfs01\QlikSenseData\Development\TelemetryDashboard\MetadataGenerater\certs\'. Error: 0.  Verify that you have sufficient privileges to modify the security permissions for this file.
> MSI (s) (B0:B0) [09:41:42:788]: Error in rollback skipped.	Return: 3
> MSI (s) (B0:B0) [09:41:42:788]: Executing op: FolderCreate(Folder=\\omfs01\QlikSenseData\Development\TelemetryDashboard\MetadataGenerater\certs\,Foreign=0,SecurityDescriptor=BinaryData,)
> MSI (s) (B0:B0) [09:41:42:788]: Note: 1: 2205 2:  3: Error 
> MSI (s) (B0:B0) [09:41:42:788]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1926 
> Info 1926.Could not set file security for file '\\omfs01\QlikSenseData\Development\TelemetryDashboard\MetadataGenerater\certs\'. Error: 0.  Verify that you have sufficient privileges to modify the security permissions for this file.

But I still got this error when running as a domain admin... and I can see that before it rolls back it manages to create some folders & files which would suggest it's got the required permission.

**Comment by Nillth** [comment]
The account needs to have full control over the share and the permissions on the folder.
The ability to set or change permissions are linked to the Full Control permission.

**Comment by alexometis** [comment]
I the log attached, I was running it as a domain admin that has full permissions on both the server where Qlik Sense resides and the file share where the Qlik root folder is. There is no more elevated permission that I can run it as I think! 

I even captured the permissions on that "certs" folder before the installer rolled back and it showed my admin user as having Full Control permissions.

**Comment by jparis** [comment]
Ok. Think I got this sorted. Feel free to give it a spin.

**Comment by alexometis** [comment]
Yep, that's worked - thanks.
