### ISSUE TITLE
Dashboard fail  Table 'FileListTemp' not found

### ISSUE THREAD

**Issue by gkrish26** [eapowertools/qs-telemetry-dashboard#33]
we are getting below error while reloading the dash board. can you please help us to fix.

The following error occurred:
Table 'FileListTemp' not found
The error occurred here:
[OrderedFileList]:
	NOCONCATENATE
	LOAD DISTINCT
        [FileName],
    	[FileTime]
	RESIDENT [FileListTemp]
	ORDER BY [FileTime] DESC

**Comment by levi-turner** [comment]
There are two sections where this temporary table is created.

1. Node RAM
2. Engine Telemetry Settings

For (1), the app assumes that there are **Service_Repository** logs in `ArchivedLogs\<nodeName>\Repository\System`.

For (2), the app assumes there are **Service_Engine** logs in `ArchivedLogs\<nodeName>\Engine\System`.

Are both of those assumptions valid for your environment? Basically based on Qlik Sense's [archival process](https://support.qlik.com/articles/000031778) I am assuming that all nodes in the site will have to have been installed for at least 12 hours. Practically, this section will fail on fresh installations.

**Comment by gkrish26** [comment]
Hi Levi,

thanks for the information. in our environment  we have more than 8 servers for dedicated services. so if a proxy enable server does not have engine\system will the app fails ? 
getting below error now.
LET vCurrentFile = Peek('FileName', i, 'OrderedFileList')
    20201120T163808.244+0100 0557 [tmp]:
    20201120T163808.244+0100 0558             LOAD 
    20201120T163808.244+0100 0559                 [Timestamp],
    20201120T163808.244+0100 0560 			    [Hostname],
    20201120T163808.244+0100 0561 			    Num(TextBetween([Message],'Total amount of system physical RAM available is: ', ' ')) AS [availableRAMtmp]
    20201120T163808.244+0100 0562 			FROM 
    20201120T163808.244+0100 0563 			'lib://ArchivedLogsFolder\AWSAEXIRL1180.XXX.COM\Repository\System\' (txt, utf8, embedded labels, delimiter is '\t', msq) 
    20201120T163808.244+0100 0564             	WHERE WildMatch([Message],'*Total amount of system physical RAM available is*')
    20201120T163808.246+0100      Error: Cannot open file: 'lib://ArchivedLogsFolder\AWSAEXIRL1180.JNJ.COM\Repository\System\' (Native Path: \\AWSAEXIRL1178\Share\ArchivedLogs\AWSAEXIRL1180.XXX.COM\Repository\System\)
    20201120T163808.250+0100      Execution Failed
    20201120T163808.255+0100      Execution finished.

**Comment by gkrish26** [comment]
Hi Levi,
I believe the dashboard script needs to review by considering cluster environments, the problem is while searching for  log file under ArchivedLogs\<nodeName>\Engine\System to create FileListTemp table will not be 100% correct by considering environment configurations. for example we have 4 node environment , on 1 node  proxy and repository services only will run. so Engine folder will not be created as the service will always disabled. 

at least the script should skip if such log files/folders  not found on archived logs ,should continue execution instead of fail.

**Comment by levi-turner** [comment]
@gkrish26 : It's not immediately obvious that this is the cause. For **Node RAM**, the app assumes that there are Service_Repository logs in `ArchivedLogs\<nodeName>\Repository\System`. Since every node needs to have a Repository Service, every node _should_ have logs here. There are two situations where I can envision this to fail:
1. New installations
2. Nodes where the **Service log level** is set to off (as opposed to the default of `Info`

![image](https://user-images.githubusercontent.com/23237561/100094917-bcbc6e80-2e27-11eb-8af0-59a4286ef369.png)

Is (2) the case for your environment?

**Comment by gkrish26** [comment]
Hi Levi,

this is not the case in our environment  as service log level set to info. let me know if any additional information help to identify the issue.

Thanks for your quick response.

**Comment by jimbocloud** [comment]
Hello,

We had the same issue on our multi-node site. I found that the task would successfully reload from the Central node but would always fail when reloading from a rim node. I found that our ArchivedLogsFolder data connection was not correctly pointing to the ArchivedLogs folder within our Qlik Share. Updating this data connection resolved the issue for us.

Hope this helps.

Thanks
James

**Comment by jimbocloud** [comment]
Hello,

We had the same issue in our multi-node site. The app would reload successfully from the Central node but it would always fail from any of our rim nodes. It turns out our ArchivedLogsFolder data connection wasn't correctly pointing to the ArchivedLogs folder within our Qlik Share. Fixing this data connection resolved the issue for us.

Hope this helps.

Thanks,
James

**Comment by aakanshashri** [comment]
Hello,

What if it is a new installation and multi node environment

I have uninstalled my previous telelmetry dashboard which was a installed and install this new application setup

after which i am getting filelisttemp not found error

what to do next to resolve this. as discussed above service log level is set to info in all nodes.

THanks
