### ISSUE TITLE
chart request

### ISSUE THREAD

**Issue by vuuuxp** [eapowertools/qs-telemetry-dashboard#35]
Hi Jesse, I was wondering where you get this chart?

<img width="761" alt="screen shot 2018-12-18 at 3 38 58 pm" src="https://user-images.githubusercontent.com/13967830/50189714-4168ee80-02db-11e9-86c6-2c293ad0c5ce.png">

**Comment by levi-turner** [comment]
It looks to be a screenshot taken from the Scalability Analyzer app with some added text at the bottom.

**Comment by qlik-peterman** [comment]
Yes, exactly.    It's a screenshot from the Scalability Analyzer app, taken from a test that was run to determine the performance impact to a server running Telemetry Logging in each of 3 modes.   This screenshot can be found in the Telemetry Dashboard documentation.   It is not generated or related to the Telemetry Dashboard itself.
