### ISSUE TITLE
Restoring the Telemetry Dashboard to a New Qlik Sense Site Question

### ISSUE THREAD

**Issue by jimbocloud** [eapowertools/qs-telemetry-dashboard#36]
As part of our upgrade process we currently migrate all content from our existing Qlik Sense site to a new one. We currently have the Telemetry Dashboard app configured in our existing site. As part of the migration of content from the existing site to the new one, all tasks, apps and data connections would be transferred over.

So I was wondering, is it necessary to run TelemetryDashboard.exe in our new site?

If we were to re-run the Telemetry Dashboard reload sequence on the new site without having run the .exe on the new Central node, would it succeed? (Note - Data Connections pointing to active log locations would have been updated to point to our new servers prior to this)

If we migrate our content to the new site and then ran TelemetryDashboard.exe, I understand the Telemetry Dashboard app, its configuration, Tasks and schedule would be overwritten. Therefore we would have to reconfigure it, causing extra manual effort. If possible we would prefer to avoid this however I understand it may not be technically possible to do so.

Kind Regards,
James

**Comment by jparis** [comment]
If you were sure you have moved all the assets over correctly (with the exact same IDs), you could just move the exe file and you wouldn't need to reinitialize it. Worst case, you try it, and if it doesn't work, you re-init. It's only ~4 assets, so hopefully isn't too much reconfig.
