### ISSUE TITLE
TelemetryDashboard-1-Generate-Metadata deleted on server restart

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#37]
I recently installed the Telemetry Dashboard on an environment, including setting the app up for their multi-node architecture etc. In my test loads it all ran fine. 

To get the Engines to be logging the QIX performance data as required, we scheduled an out of hours restart of services.

When we logged in the next morning, the TelemetryDashboard-1-Generate-Metadata task had been deleted. I checked QMC Changelog in Operations Monitor and couldn't find any reference to it being deleted and checked with other admins and no-one had deleted it. 

Is there a known issue with it disappearing? Is there a workaround to reinstate the task? If I run Initialize won't it delete my altered app & data connection settings?

**Comment by levi-turner** [comment]
@alexometis : If you were to run `TelemetryDashboard.exe -initialize` (from https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Command-Line-Flags), it would indeed publish and replace the app. What changes are you concerned about? 

I did develop this PowerShell script (https://gist.github.com/levi-turner/18f2c4db12c948ae8709d3cca34aecfd) to rebuild tasks + schedule the fetch. It may be relevant here.

**Comment by alexometis** [comment]
I changed the time & date format, configured multi-node and also made a couple of new sheets with slightly different analysis. I could rename the app I presume, run initialise and then link the task to my renamed copy of the app? 

The PowerShell looks really useful though - esp. as it sets a schedule - will look at that in the new year.

**Comment by jparis** [comment]
closing old issue. re-open if it's still a problem
