### ISSUE TITLE
Task is failing looking for empty file while loading 

### ISSUE THREAD

**Issue by sivajisrinivas** [eapowertools/qs-telemetry-dashboard#38]
Num(TextBetween([Message],'Total amount of system physical RAM available is: ', ' ')) AS [availableRAMtmp]
 			FROM 
			'lib://ArchivedLogsFolder\XXXXX\Repository\System\' (txt, utf8, embedded labels, delimiter is '\t', msq) 
             	WHERE WildMatch([Message],'*Total amount of system physical RAM available is*')

**Comment by levi-turner** [comment]
I am not entirely sure how this could occur outside of the edge scenario of trying to reload this app on a site which either itself or a node has not run for 12 hours. Every node has to have a Repository Service and logs will archive on a cadence of 12 hours / 8MB / service restart.

Does the above fit your scenario?

**Comment by jparis** [comment]
closing old issue.
