### ISSUE TITLE
Installer cannot find Apps and StaticContent folders

### ISSUE THREAD

**Issue by AndyMarshall1962** [eapowertools/qs-telemetry-dashboard#38]
The installer can reach the QS shared file space but the sub-folders are not named as expected and fails to find them. I can't find a way to change the folder names it expects to see. Can this be changed?
If I can't change the folder names it is looking for what needs to be done to change the folders themselves and get QS to recognise this change across all nodes?

**Comment by levi-turner** [comment]
@AndyMarshall1962 : Can you clarify a bit more which folders you're referring to?

**Comment by jparis** [comment]
Hey Andy,

What error do you get specifically? I remember adding a check for apps and a few other folders (see code snippit below)

`if (!(dirs.Contains("Apps") || dirs.Contains("ArchivedLogs") || dirs.Contains("CustomData") || dirs.Contains("StaticContent")))
				{
					session.Message(InstallMessage.Warning, new Record() { FormatString = "Installer did not find an 'Apps', 'StaticContent', 'ArchivedLogs' or 'StaticContent' folder. Install will proceed but Telemetry Dashboard may not function if not installed in root Qlik Sense share folder." });
				}`

but it should still succeed. If it's failing, then that's a bug on my part, but curious exactly where?

**Comment by AndyMarshall1962** [comment]
Installer did not find an "Apps","StaticContent","ArchivedLogs" folder. It says the install will proceed but the only button available is cancel. If it can't find these folders what would happen if it did proceed, would it be left in a working state? What kind of clean-up action would be required.

**Comment by jparis** [comment]
So you could just create an 'Apps' folder, and the installer would succeed. Then delete it directly after. The telemetry dashboard would work as expected, and the uninstall would also work as expected, it's just one step when validating the path for the install.

So for the interm, you can do that. You only need one of the folders, and there doesn't need to be anything in it. That said, that's most definitely a bug in the installer, so I'll get that fixed today probably and get out a dot release with the update.

**Comment by AndyMarshall1962** [comment]
I created folders with the names it wanted and got past the error I was hitting. Now I get the message "TelemetryDashboard Setup Wizard ended prematurely". Igoes on to say it was because of an error and your system has not been modified. Is there somewhere that I can find more details.

**Comment by jparis** [comment]
Open a command prompt and use the following command:

`msiexec /i "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"`

obviously with the telemetry dashboard msi, and whatever file you want to be created for the log. Then send it over or post it here and I can take a look.

**Comment by AndyMarshall1962** [comment]
I found this in the event log.
Windows Installer installed the product. Product Name: TelemetryDashboard. Product Version: 2.0.2.0. Product Language: 1033. Manufacturer: EA Americas. Installation success or error status: 1603.

**Comment by jparis** [comment]
Sounds like a custom action failed. Can you find any errors or exceptions in the log?

**Comment by AndyMarshall1962** [comment]
There is nothing more in the event logs. Does it write a file log somewhere?

**Comment by jparis** [comment]
Yep, two posts up, you can run the msi with that command, but it'll look like:

`msiexec /i "C:\TelemetryDashboard.msi" /L*V "C:\loggingOutput.txt"`

should generate a file called loggingOutput.txt

**Comment by AndyMarshall1962** [comment]
Well blow me down with a feather, I did it from an admin cmd and it finished without error this time. Thanks for your help. If I run into this next time (I have 8 to do) I'll try this again.

**Comment by jparis** [comment]
ah ok. then it's a permissions thing in one of the custom actions. good to know. If you run into it again, run it in a non admin command prompt and i'm assuming it would fail. feel free to post/send over the logs and I can try to figure out what it is. thanks!

**Comment by jparis** [comment]
Closing this for now.
