### ISSUE TITLE
can we see an app response time screenshot within the telemetry dashboard in the future?

### ISSUE THREAD

**Issue by vuuuxp** [eapowertools/qs-telemetry-dashboard#39]
Hi, looking at the telemetry dashboard, I see that the chart for response time is very useful, can we see this in the telemetry dashboard with real user data? I know you can generate this with the scalability tools but that tools do not uses real usage data but instead generate the data.

Vu

**Comment by qlik-peterman** [comment]
Have you installed the package for Telemetry Dashboard and run it in your environment (to get real data)?   The short answer is yes, it is meant to show real user data.   It gets this data from the logs, and a new setting that needs to be enabled to produce some new logging.    Please read through the installation instructions and see if you can get it running.   It will then be pulling your data into the dashboard.
