### ISSUE TITLE
engineInfos.csv is missing

### ISSUE THREAD

**Issue by royceroyduya** [eapowertools/qs-telemetry-dashboard#40]
We installed latest telemetry dashboard on both single node and multinode. It is working perfectly on the multinode environement however on we are having error while the app is reloading. Upon checking on the reload log. it is getting an error when retrieving data from engineInfos.csv with an error "Cannot open file: 'lib://TelemetryMetadata/engineInfos.csv" and checking the path, the output folder under TelemetryDashboard is not availble.

**Comment by jparis** [comment]
Is the whole folder missing, or just the `engineInfos.csv` file?

**Comment by royceroyduya** [comment]
Hi jparis,

It is the whole folder that is missing.

**Comment by jparis** [comment]
looks like the fetch metadata isn't running, what do the logs say?

**Comment by jparis** [comment]
Reopen if you have a follow up.
