### ISSUE TITLE
OpenApp Timed Out - How to increase the timeout?

### ISSUE THREAD

**Issue by SusanHS** [eapowertools/qs-telemetry-dashboard#42]
Hei
Please instruct how to increase the timeout?

![OpenAppTimeOut](https://user-images.githubusercontent.com/64188274/116543211-46e89180-a8f6-11eb-891b-be43adda7464.PNG)

Best regards,
Susan

**Comment by jparis** [comment]
fix coming in next release

**Comment by jparis** [comment]
added in v4.3.0

-enginetimeout flag
