### ISSUE TITLE
ErroPeakMemoryMs not configured?

### ISSUE THREAD

**Issue by SusanHS** [eapowertools/qs-telemetry-dashboard#43]
Hey
2 issues.
1. AvailableRAMMB. Is it the total RAM available for QS engine? If yes, I think the number is incorrect for some of our engines. Do you know where to investigate next?
2. How to fix the '... not configured'?

![image](https://user-images.githubusercontent.com/64188274/116548200-8f0ab280-a8fc-11eb-9186-b8e7a3187883.png)

Best regards,
Susan

**Comment by levi-turner** [comment]
@SusanHS : Due to how problematic gathering this data is, I plan to deprecate this entire table. It's only used for informational or minor cosmetic purposes.

**Comment by SusanHS** [comment]
Can you give a workaround before the bug fix is available? Now our calculations doesn't work because of the '... not configured' value in that table.

**Comment by rzenere-methode** [comment]
Hey @levi-turner,
thanks for confirming the table will be deprecated. Do you have an ETA for the next release?

Many thanks for your work,
Riccardo

**Comment by jparis** [comment]
fixed 2nd part to this. closing.
