### ISSUE TITLE
Rim nodes not logging as expected

### ISSUE THREAD

**Issue by AndyMarshall1962** [eapowertools/qs-telemetry-dashboard#43]
We are seeing full logging as requested for the central node but rim nodes are essentially silent. The file is created witha basic record showing that logging is enabled but even with level set to INFO we get nothing. Even events exceeding threshold log nothing. Is there a sub we need to be aware of or some special parameter relating to rim nodes I missed. This is relevant to an escalation we currently have with Qlik so would really appreciate a quick answer on this. I think Chip has created a PI for this issue aving replicated it in support.

**Comment by qlik-peterman** [comment]
Are you copying the Telemetry settings into each engine's Settings.INI file?   You want them to match, and not to just have that INI file changed on the central node.   I realize it's a bit redundant, but each engine gets its own settings from its own INI file, and the Telemetry isn't yet controlled from the QMC, so you have to set it by engine.

**Comment by levi-turner** [comment]
@AndyMarshall1962 : On my end, I am not seeing a differential expression of telemetry data across nodes.

Test case:
- Telemetry setup for obscenely low settings:
```
[Settings 7]
ErrorPeakMemory=200
WarningPeakMemory=100
ErrorProcessTimeMs=20
WarningProcessTimeMs=10
```
- Separate virtual proxies load balanced to specific Engines; all VPs provided by the Central node
- Same app opened

Results:
- 20 hits for ERRORS when opening a copy of the Operations Monitor across each node

Based on this, if you are getting differential volume of Telemetry data, then that suggests differential session activity across those nodes (either more sessions, more computationally complex sessions,).

**Comment by AndyMarshall1962** [comment]
We are still seeing some nodes logging onto a header and verbosity record and no actual data. This is not justified by activity on the node (or lack thereof).

**Comment by levi-turner** [comment]
As best I can tell, this issue is no longer occurring, yes?

**Comment by AndyMarshall1962** [comment]
We have not seen this problem on user facing environments, it still seems to fail some times on our engineering sites. This is annoying but not a priority so I closed the case in the Qlik support portal. I still believe there is something wrong here but I can't fight every battle.

**Comment by levi-turner** [comment]
Fair enough. From a delivery perspective, this project builds off the logging so we won't have a whole ton of insight into why the logging isn't being produced. I'd encourage going through Qlik Support if this issue continues or begins to be a problem.
