### ISSUE TITLE
Strange values in AppName

### ISSUE THREAD

**Issue by SusanHS** [eapowertools/qs-telemetry-dashboard#44]
Hei
I checked the $\TelemetryDashboar\output\apps.csv. All values are correct there.
But why from hub, I see this? how to fix it?

![image](https://user-images.githubusercontent.com/64188274/116550994-17d71d80-a900-11eb-9f2d-fac412e3772d.png)

Best regards,
Susan

**Comment by levi-turner** [comment]
@SusanHS : The underlying QIX Performance logs would then have apps which have since been deleted. Since they have seen been deleted, we do not have the relevant information to be able to list a friendly name.
