### ISSUE TITLE
Problem installation by .exe

### ISSUE THREAD

**Issue by Cocuzzan** [eapowertools/qs-telemetry-dashboard#47]
Hi. I've this error

C:\Users\Administrator\Downloads>TelemetryDashboard.exe -initialize
1       2021-05-21T14:01:21.2190950Z    Info    Arguments handled and logging initialized.
2       2021-05-21T14:01:21.4870142Z    Info    Preparing to run initialize mode, this will create two tasks, import an application and create two data connections in your environment, press 'q' to quit or any other key to proceed:
j3      2021-05-21T14:01:25.8492892Z    Info    Please enter the 'DOMAIN\user' for the service account running Qlik Sense Enterprise (without quotes, example: QLIK\jparis):
IP-AC1F2D70\ThBT2SvcU
4       2021-05-21T14:01:45.7179874Z    Info    The user 'IP-AC1F2D70\ThBT2SvcU' was entered.
5       2021-05-21T14:01:45.7258095Z    Info    Initialize Mode:
6       2021-05-21T14:01:45.7326446Z    Info    Running in initialize mode.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '\\IP-AC1F2D\Qlik Sense Storage\TelemetryDashboard' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.Run(String serviceAccount)
   at qs_telemetry_dashboard.TelemetryDashboardMain.Main(String[] args)

**Comment by jparis** [comment]
Looks like the user running the exe doesn't have access to the share. Either run the exe with a user that has access OR in a few days I'll release a new version that allows a 'manual' install flow.

Closing this.
