### ISSUE TITLE
Installation not found in the control panel

### ISSUE THREAD

**Issue by asmitamkhrj** [eapowertools/qs-telemetry-dashboard#50]
Hello,

We have installed telemetry v4.2.2 - Telemetry Dashboard in our system , but cannot spot the same installation in the control panel.
The installation is a success as we can see the upgraded telemetry version in the environment, but we cannot spot the installation directories. This might create a problem for future installation of telemetry. Could you please help ?

Br, Asmita.

**Comment by jparis** [comment]
The telemetry dashboard is no longer an installable, it's simply just a self-contained .exe. There are no keys/temp files as there would normally exist with an installer. There were too many isssues with the existing installer, so we decided to go down this route instead.

To delete it, you can simply just delete the .exe file and you're done. If you want to upgrade, you can just overwrite the .exe file.

the .exe is in your qlik share folder/TelemetryDashboard
