### ISSUE TITLE
cyrillic characters not show correct.

### ISSUE THREAD

**Issue by strelokr** [eapowertools/qs-telemetry-dashboard#51]
Cyrillic names objects  are displayed incorrectly. Because of this, it is impossible to use the system. you can hardly guess what this object is.
![image](https://user-images.githubusercontent.com/7746497/52400268-5dad2e80-2ac7-11e9-835d-764273699d07.png)

**Comment by levi-turner** [comment]
Please provide the app name as represented in the QMC so we can do some testing.

**Comment by strelokr** [comment]
For Example
![image](https://user-images.githubusercontent.com/7746497/52412114-842e9200-2ae6-11e9-83c1-da95d446bf6a.png)
1. Етап планування - Planning stage
2. Етап закупівель - Purchasing stage

**Comment by levi-turner** [comment]
So we'll work on a released fix, but for you, in the short-term:

- Go to the Script
- Go to the Metadata section of the script
- Line 38 or where it says `(txt, codepage is 28591, embedded labels, delimiter is '`', msq);`
- Change to `(txt, codepage is 65001, embedded labels, delimiter is '`', msq);`

You didn't report it but swapping the codepage out on other CSVs loads in there may be needed as well.

Let me know if that works for you.

**Comment by strelokr** [comment]
It's works for me. Thanks!
