### ISSUE TITLE
We like to look the data at app level on how much RAM each is app being consumed, when a user opens the app from hub

### ISSUE THREAD

**Issue by sujithgudipudi** [eapowertools/qs-telemetry-dashboard#53]
We like to look the data at app level on how much RAM each is app being consumed, when a user opens the app from hub

**Comment by levi-turner** [comment]
We will look into the feasibility of providing this type of data. This level of granularity would only be available on the INFO level of the QIX logs which will net you a ~5.5% degrade in response time, all else being equal (https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Logging-Performance).

**Comment by jparis** [comment]
Fixed: https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/3.0.0
