### ISSUE TITLE
Installing Telemetry Dashboard on Cluster

### ISSUE THREAD

**Issue by ajradford** [eapowertools/qs-telemetry-dashboard#54]
Hey, sorry if this has been discussed but is there a way to install on a QS Cluster where the Repository is installed on a separate host?  Or is the only supported configuration where the DB is installed on the Central Node?

**Comment by levi-turner** [comment]
Let's distinguish two distinct components:

1. Qlik Sense Repository Service
2. Qlik Sense Repository Database or alternative PostgreSQL standalone installation

The Telemetry installer needs to be installed on a server which has (1). Where (2) lives is irrelevant.

**Comment by ajradford** [comment]
Hey Levi thanks for quick response.  The Central node has 1. installed on it and 2. resides on a separate host.  As you are saying the install should work under the existing config; the error has been that the QRS is not contactable.  I will double check and come back to you.

**Comment by ajradford** [comment]
Hey Levi, I tried installing again and selected the install path on the remote host were the Qlik sense share is located.  I can see that some files were created when the install started but it came back with same error the QRS cant be contacted.  In screenshot you can see the service running on the server I am running the Telemetry install.

![image](https://user-images.githubusercontent.com/47580965/52757460-9cb02680-3069-11e9-8be9-9fa984008851.png)

![image](https://user-images.githubusercontent.com/47580965/52757451-9326be80-3069-11e9-8c09-364bd80b5cbc.png)

**Comment by jparis** [comment]
If it can't contact the repository, then the communication to localhost is failing for some reason. If you have the opportunity to debug using c# the exact code that's being run is: 
` MakeQrsRequest("/about", HTTPMethod.GET);`

which in turns runs:
```string xrfkey = "0123456789abcdef";
HttpWebRequest request = (HttpWebRequest)WebRequest.Create(@"https://localhost:4242/qrs" + path + "xrfkey=" + xrfkey);
request.Method = method.ToString();
request.Accept = "application/json";
request.Headers.Add("X-Qlik-xrfkey", xrfkey);
request.Headers.Add("X-Qlik-User", @"UserDirectory=internal;UserId=sa_api");
// Add the certificate to the request and provide the user to execute as
request.ClientCertificates.Add(SENSE_CERT.Value);```

It uses the certs at C:\ProgramData\Qlik\Sense\Repository\.Exported Certificates.

The installer needs to run as admin to get access to above folder.
