### ISSUE TITLE
Telemetry App fails when reloading node doesn't have Telemetry logging configured

### ISSUE THREAD

**Issue by levi-turner** [eapowertools/qs-telemetry-dashboard#55]
Fix:

Build a table and concat into it:

```
QIXPerformance_Engine:
LOAD * INLINE [
Timestamp, LogTime, HourNbr, Level, Hostname, Logger, Thread, Id, ServiceUser, Message, ProxySessionId, ActiveUserDirectory, ActiveUserId, EngineTimestamp, EngineThread, ProcessId, CServerId as SessionId, Server Started, Method, Request Filter, RequestId, Target, RequestException, AnyException, ProcessTime, WorkTime, LockTime, ValidateTime, TraverseTime, Handle, DocId, AppID-DocId, ObjectId-VisualizationID,  NetRAM,  PeakRAM,  ObjectType,  Id2, LogObjectID, FileName, FilePath() AS FilePath, FileDir, LogSubType, LogArchive
 ];
```

**Comment by gorkor** [comment]
Yes, but skip the "As" stuff, or you will get some not-expected filed names ....

QIXPerformance_Engine:
LOAD * INLINE [
Timestamp, LogTime, HourNbr, Level, Hostname, Logger, Thread, Id, ServiceUser, Message, ProxySessionId, ActiveUserDirectory, ActiveUserId, EngineTimestamp, EngineThread, ProcessId, SessionId, Server Started, Method, Request Filter, RequestId, Target, RequestException, AnyException, ProcessTime, WorkTime, LockTime, ValidateTime, TraverseTime, Handle, DocId, AppID-DocId, ObjectId-VisualizationID,  NetRAM,  PeakRAM,  ObjectType,  Id2, LogObjectID, FileName, FilePath, FileDir, LogSubType, LogArchive
 ];

**Comment by levi-turner** [comment]
Indeed, fair point. Thanks for the eye. It was something thrown together live debugging an issue.

**Comment by jparis** [comment]
fixed: https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/3.0.0
