### ISSUE TITLE
Still a hardcoded 7 hour offset

### ISSUE THREAD

**Issue by gorkor** [eapowertools/qs-telemetry-dashboard#56]
v2.0.3 release:

there is yet a hardcoded 7 hour offset.
This is in the "Sessions archive" tab of the load script:

Timestamp("Session Start"-Time#(7,'hh')) as Session_Start,

**Comment by levi-turner** [comment]
Looking into things

**Comment by levi-turner** [comment]
So after digging in, what is the issue? On my end, I am not seeing an inaccurate representation of the session time.

**Comment by levi-turner** [comment]
Closing this issue out since I am not seeing a response. Please reopen should the issue present or more info can be provided. In the testing I did, I ensured that the local time was not -7 UTC and the logs + app agreed on the timestamp of the session(s).
