### ISSUE TITLE
Error Installation of Telemetry. More than 1 Cluster.

### ISSUE THREAD

**Issue by Darwin5050** [eapowertools/qs-telemetry-dashboard#59]
Hi, we had the following error when installing the Telemetry component.
How can we define the path of the corresponding cluster?

<img width="721" alt="Error_telemetry" src="https://user-images.githubusercontent.com/85948856/122072944-08376980-cdc6-11eb-94a7-164ca1e3ba0b.png">

**Comment by levi-turner** [comment]
There should not be multiple service clusters. I would encourage working with Qlik Support to help clean up the non-expected setup of your environment's database.

**Comment by Darwin5050** [comment]
@jparis , what do you recommend in this case ?

**Comment by jparis** [comment]
What Levi said. An environment should not have more than 1 cluster.
