### ISSUE TITLE
Is this false positive or malicious?

### ISSUE THREAD

**Issue by Justformoment** [eapowertools/qs-telemetry-dashboard#60]
Hi Team,

We were going to install Telemetry Dashboard v4.4.0 on our environment, but before doing that we scanned an executable file via https://virustotal.com and it identifies the file as malicious. Is this false positive?

![image](https://user-images.githubusercontent.com/26446355/123132372-f8b3c280-d44e-11eb-99eb-ff255c857643.png)

Thanks

**Comment by jparis** [comment]
I guess it depends on what it considers malicious? What are the details around the failure? You can look through the code and dependencies and decide for yourself.
