### ISSUE TITLE
sa_api accesses sheets, which messes up Operations Monitor

### ISSUE THREAD

**Issue by tengstam** [eapowertools/qs-telemetry-dashboard#63]
In operations monitor, sheet usage, we are usually analyzing sheets that can be removed due to not being used. Since moving to 4.2.2 all sheets are "accessed" each day by sa_api. 

Meaning we can no longer delete sheets upon criteria not used
![sheet usage](https://user-images.githubusercontent.com/42960415/124575843-094f3a00-de4c-11eb-992a-2e6b3def96ce.PNG)

Qlik Sense May2021
Telemetry 4.2.2

**Comment by levi-turner** [comment]
@jparis : I can't envision why this behavior would change, agree?

**Comment by jparis** [comment]
Haven't changed anything here. I would have guessed that all apps would have been last accessed by sa_api, or none, but it seems like not all of them have that... so is there another service that's doing somethign with the app?

**Comment by levi-turner** [comment]
Added a doc call out here: https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Installation#considerations-when-using-sheet-usage-metrics-from-the-operations-monitor

This is fantastic stuff, @jurajmisina !
