### ISSUE TITLE
Failed to install "The install directory as not valid"

### ISSUE THREAD

**Issue by cleveranjos** [eapowertools/qs-telemetry-dashboard#64]
[MSI79a6b.LOG](https://github.com/eapowertools/qs-telemetry-dashboard/files/3065191/MSI79a6b.LOG)

**Comment by jparis** [comment]
What is the path you used for the install directory?

**Comment by cleveranjos** [comment]
\\QMI-QS-SN\QlikShare\TelemetryDashboard\

Running into a QMI machine
![Annotation 2019-04-10 152049](https://user-images.githubusercontent.com/9040310/55903522-3e547f80-5ba4-11e9-88ef-93e50a4c8b46.png)

**Comment by jparis** [comment]
Just wanted to make sure you have double backslash?
`\\QMI-QS-SN\QlikShare\TelemetryDashboard\`

**Comment by cleveranjos** [comment]
tried with and without, both generate same error

**Comment by levi-turner** [comment]
@cleveranjos : I am not seeing this with that QMI.

Steps done:
 - Logged in as vagrant
 - Ensured access to `C:\ProgramData\Qlik\Sense\Repository\Exported Certificates` (https://youtu.be/EPLl1BODwH4?t=78)
 - Path used: `\\QMI-QS-SN\QlikShare\TelemetryDashboard\`

**Comment by cleveranjos** [comment]
Logged in as vagrant 
Ensured access to C:\ProgramData\Qlik\Sense\Repository\Exported Certificates (https://youtu.be/EPLl1BODwH4?t=78)
Path used: \\QMI-QS-SN\QlikShare\TelemetryDashboard\

**Comment by levi-turner** [comment]
Caused by a previous installation of the Telemetry Dashboard. Due to a bug in that previous installer an uninstallation is needed.
