### ISSUE TITLE
Missing sheet 

### ISSUE THREAD

**Issue by Justformoment** [eapowertools/qs-telemetry-dashboard#65]
After upgrading to the latest version(4.4.1), we can't see information about sheet and object. the executable file works fine, I mean it fetches metadata without any issue and the app reloads without problem
![image](https://user-images.githubusercontent.com/26446355/125965963-948b00d6-9638-46a9-a990-9452b85fb520.png)

**Comment by Justformoment** [comment]
@jparis, could you please help us? thanks

**Comment by levi-turner** [comment]
In the attached screenshot you are showing only `OpenApp` events, which obviously do not have a Sheet or Object because a sheet or open hasn't been accessed (yet).

If you drill into the *Visualization Objects Only* filter, do you see any sheets?

**Comment by Justformoment** [comment]
No, it still doesn't show
![image](https://user-images.githubusercontent.com/26446355/126498440-8c4c241c-eca6-42e2-8bc1-c85aff7f97fe.png)

**Comment by levi-turner** [comment]
So for the `SheetList` object, I can't do anything about that. That's an Engine call to get a list of sheets so logically the sheet name makes no sense. For the `sheet` object, it should have a name.

**Comment by Justformoment** [comment]
thank you for your input
