### ISSUE TITLE
Error reloading the app

### ISSUE THREAD

**Issue by cleveranjos** [eapowertools/qs-telemetry-dashboard#65]
This line above caused a "field not found"
I´ve commented and reloaded fine
// Clean entries in QIXPerformance_Engine table
Drop field CacheBytesAdded from QIXPerformance_Engine;

**Comment by levi-turner** [comment]
Meaning you commented out `Drop field CacheBytesAdded from QIXPerformance_Engine;`?

Do you have a script log from the failing reload?

**Comment by cleveranjos** [comment]
yes, I commented. please find attached the log with error
2019-04-10 20:54:04 0577 Drop field CacheBytesAdded from QIXPerformance_Engine
2019-04-10 20:54:04      Error: Field 'CacheBytesAdded' not found

[Reload task of Telemetry Dashboard.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/3065833/Reload.task.of.Telemetry.Dashboard.log)

**Comment by levi-turner** [comment]
That implies that it's not getting data from the `Engine Performance Root` and `Engine Performance Archives` sections of the script where the field is brought in initially. Was this reloaded in the QMC? Are there log files matching the string `Performance_Engine`?

**Comment by cleveranjos** [comment]
Yes, reloaded through QMC
Attaching the log file (i´ve changed my log level to INFO previously )
[QMI-QS-SN_QixPerformance_Engine.txt](https://github.com/eapowertools/qs-telemetry-dashboard/files/3065933/QMI-QS-SN_QixPerformance_Engine.txt)

**Comment by cleveranjos** [comment]
Under \Engine\Trace there is no \*_Performance_Engine but there´s is a 
QMI-QS-SN_QixPerformance_Engine.txt

**Comment by levi-turner** [comment]
What is the logging level for the **Performance log level** under QMC > Engines > Edit > Logging?

**Comment by cleveranjos** [comment]
![Annotation 2019-04-11 102504](https://user-images.githubusercontent.com/9040310/55961227-c2f6da80-5c44-11e9-9611-6bedcb86fa49.png)

**Comment by levi-turner** [comment]
Please change that log to at least INFO, which is the default. At any other level there are no performance metrics for the Engine (e.g. RAM usage) which is consumed by the Telemetry Dashboard, as well as let's say the Operations Monitor.

**Comment by cleveranjos** [comment]
Fixed!
Maybe this heads up should be included into wiki, since only QIX Performance log level is mentioned

Thank you, @levi-turner

**Comment by levi-turner** [comment]
Fair enough.
