### ISSUE TITLE
Installation issue - System Unauthorized Access Exception

### ISSUE THREAD

**Issue by armandfrigo** [eapowertools/qs-telemetry-dashboard#66]
Hi,

We have quite a number of enforced security policies on our servers.

When we run the installer, we get the attached error message.
We have tried executing the .exe file with admin privileges of course and an account who is part of the local adminstrators group.
There is nothing useful in the log file, same in the Windows system logs.

Is there any other way to deploy, manually, the Telemetry dashboard?
Or a debug mode to better understand where it crashes?

![2021-07-21_13-53-08](https://user-images.githubusercontent.com/9445066/126502850-28110466-bf79-4881-b3fb-3925562ab73f.png)

**Comment by jparis** [comment]
So there is a `-skipcopy` flag that you can use for this exact reason.

Run the telemetry dashboard again with that flag, and while you will need to enter a user, it won't use that user to try to perform any operations. That DOES MEAN you will need to put the telemetry dashboard in the correct location on disk. 

Some info is here: https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Command-Line-Flags
(look for the flag), and more info will be provided during initialize.

Will close this for now, re-open if you run into issues.
