### ISSUE TITLE
Telemetry Dashboard Install Stopped Working

### ISSUE THREAD

**Issue by V1NW** [eapowertools/qs-telemetry-dashboard#67]
Hello,

Recently we have upgraded the version to May 2021 SR4.

And we have tried to upgrade the telemetry dashboard as well.

We run the installer it stopped working and cannot be installed.

Please find the error logs

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

E:\QS Storage\Private\Shared>TelemetryDashboard.exe -initialize
1       2021-07-28T08:55:55.8182327Z    Info    Arguments handled and logging in
itialized.
2       2021-07-28T08:55:56.0502575Z    Info    Preparing to run initialize mode
, this will create two tasks, import an application and create two data connecti
ons in your environment, press 'q' to quit or any other key to proceed:
3       2021-07-28T08:55:58.5419466Z    Info    Please enter the 'DOMAIN\user' f
or the service account running Qlik Sense Enterprise (without quotes, example: Q
LIK\jparis):

5       2021-07-28T08:56:05.6364990Z    Info    Initialize Mode:
6       2021-07-28T08:56:05.6364990Z    Info    Running in initialize mode.
7       2021-07-28T08:56:16.8175934Z    Info    A single existing App 'Telemetry
Dashboard' was found.

Unhandled Exception: qs_telemetry_dashboard.Exceptions.InvalidResponseException:
 OK returned when trying to replace Telemetry Dashboard app. Request failed.
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.ImportApp()
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.Run(String service
Account, Boolean skipCopy)
   at qs_telemetry_dashboard.TelemetryDashboardMain.Main(String[] args)

**Comment by jparis** [comment]
I think you might be on an older version of telemetry, if you grab the latest it should be fixed.
