### ISSUE TITLE
Unable to scheduleTask to run automatcally and onlyit shows current day data

### ISSUE THREAD

**Issue by Abhinovqlik** [eapowertools/qs-telemetry-dashboard#68]
Hello Team
1. Im unable to set the task which will run automatcally on task scheduled time.
2. When I am running the task manually,  when I see the data or app Usage of much each data is taking. I can see only Cureent day data. I need to see the pervious days.

Can anyone help Please

**Comment by levi-turner** [comment]
@Abhinovqlik : Which task are you trying to schedule?

Out of the box there are two tasks:

1. Generate the App Metadata
2. Reload the Qlik App

(1) is unscheduled and (2) is linked to (1).

If you'd like to schedule (1) then please refer to https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata

**Comment by Abhinovqlik** [comment]
Hi Turner,
Thanks for repsonse. I am planning to schedule Generate app Metadata. 

Currently, I m running the task manually, when I check the data I dont see the pervious data in the details sheets, I need past one week or one month data. How much each app as taken.

Thanks in Advance
![Date](https://user-images.githubusercontent.com/50502205/57656114-63198980-758c-11e9-9971-70bc74179c18.PNG)

**Comment by Abhinovqlik** [comment]
@levi-turner  this any solution on this. I trying to get the data for pervious dates or When I ran the task manually it doesnt save the date..As shown in above scrrenshot.

**Comment by levi-turner** [comment]
@Abhinovqlik : By default the app should have 30 days worth of data. Please check the following parts:

1. Open the app > Data Load Editor > **Variables & Config** section of the load script > `v#LogDays` : Confirm this is to set to 30
2. QMC > Confirm that the path defined in the `ArchivedLogsFolder` data connection matches the path defined in QMC > Service Cluster > `Archived logs root folder`

**Comment by Abhinovqlik** [comment]
@levi-turner : Thank you
1. v#LogsDays: was set to 60 days. I have changed it to 30 days and ran the telemetry dashboard. Still it shows only today date. I need Last 30 days.
2. In QMC everything looks good as you mentioned
![error  telemetry](https://user-images.githubusercontent.com/50502205/58037657-c18dbd00-7ae2-11e9-86c0-872571857ae1.PNG)

**Comment by levi-turner** [comment]
@Abhinovqlik : Please provide the script log then

**Comment by Abhinovqlik** [comment]
@levi-turner Attached Script Logs from 
[866ebbe3-a10f-4bfc-8fdf-b384fe5c8235.2019_05_20_16_43_06.3A7EF739DDA292BB4AE3.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/3198915/866ebbe3-a10f-4bfc-8fdf-b384fe5c8235.2019_05_20_16_43_06.3A7EF739DDA292BB4AE3.log)

**Comment by levi-turner** [comment]
That's an older copy of the app. Please use this version of it.
[Telemetry Dashboard.zip](https://github.com/eapowertools/qs-telemetry-dashboard/files/3199060/Telemetry.Dashboard.zip)

**Comment by Abhinovqlik** [comment]
Do I need to upload this QVF to the exsisting Telemetry dashboard or its new version of Telemetry Dashbaord

**Comment by levi-turner** [comment]
It's just a Qlik app which builds off the meta-data generation task. So you can upload it to the QMC and reload it.

**Comment by Abhinovqlik** [comment]
@levi-turner  thanks for dashboard. Do i need to uninstall pervious Telemetry Dashboard.
 I am seeing 2 task in the QMC task and One right now which you sent.
1. Telemetry Dashboard-1-Generate-metadata
2. Telemetry Dashboard-2-reload-dashboard

The one you sent I ran it and scheduled it.

**Comment by levi-turner** [comment]
@Abhinovqlik : Not necessarily. You can just import the QVF, associate the new app with the 2nd reload task and be done with things. Are things working?

**Comment by Abhinovqlik** [comment]
@levi-turner Thank a lot. But, we need a small session from you so that we can get to know how this app will be working and we have some questions how to use it in depth.
can you please let us know.

**Comment by levi-turner** [comment]
Have you seen the video that we produced on the app itself:  https://youtu.be/2BfZDxODhzE ?

**Comment by levi-turner** [comment]
Referred to previously compiled docs. Plan to post a more robust explainer on https://community.qlik.com/t5/Qlik-Architecture-Deep-Dive-Blog/bg-p/qlik-architecture-deep-dive-blog later in the summer.

**Comment by Abhinovqlik** [comment]
@levi-turner  we have some questions on the dashboards, Is there a way that we can setup a call? that would be more helpfull for us. 
we are good now, We can see the pervious days logs too.
