### ISSUE TITLE
Rolling back Telemetry dashbaord while installation   

### ISSUE THREAD

**Issue by abhinov04** [eapowertools/qs-telemetry-dashboard#69]
Hello Team,

When I am trying to Install Telemetry Dashboard, It goes till end it copy file and it rolls back again.

I have installed in one of my server successfully and I'm trying to install in another one.

**Comment by levi-turner** [comment]
Can you post the install log from %TEMP% (https://youtu.be/EPLl1BODwH4?t=174)?

**Comment by abhinov04** [comment]
[MSI17a18.LOG](https://github.com/eapowertools/qs-telemetry-dashboard/files/3188426/MSI17a18.LOG)

**Comment by levi-turner** [comment]
The relevant trace is
```
Calling custom action CustomActions!CustomActions.CustomActions.ImportApp
CustomAction ImportAppAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 16:59:52: InstallFinalize. Return value 3.
MSI (s) (74:34) [16:59:52:052]: Note: 1: 2265 2:  3: -2147287035 
```
@jparis : Thoughts on what would cause a failure for the *ImportApp* custom action?

The relevant code is:
```
public static ActionResult ImportApp(Session session)
{
	Tuple<HttpStatusCode, string> apps = MakeQrsRequest("/app/full?filter=name eq 'Telemetry Dashboard'", HttpMethod.Get);
	if (apps.Item1 != HttpStatusCode.OK)
	{
		return ActionResult.Failure;
	}
	JArray listOfApps = JArray.Parse(apps.Item2);
	if (listOfApps.Count == 1)
	{
		string appID = listOfApps[0]["id"].ToString();
		Tuple<HttpStatusCode, string> replaceAppResponse = MakeQrsRequest("/app/upload/replace?targetappid=" + appID, HttpMethod.Post, HTTPContentType.app, Properties.Resources.Telemetry_Dashboard);
		if (replaceAppResponse.Item1 == HttpStatusCode.Created)
		{
			return ActionResult.Success;
		}
	}
	else
	{
		if (listOfApps.Count > 1)
		{
			for (int i = 0; i < listOfApps.Count; i++)
			{
				listOfApps[i]["name"] = listOfApps[i]["name"] + "-old";
				listOfApps[i]["modifiedDate"] = DateTime.UtcNow.ToString("s") + "Z";
				string appId = listOfApps[i]["id"].ToString();
				Tuple<HttpStatusCode, string> updatedApp = MakeQrsRequest("/app/" + appId, HttpMethod.Put, HTTPContentType.json, Encoding.UTF8.GetBytes(listOfApps[i].ToString()));
				if (updatedApp.Item1 != HttpStatusCode.OK)
				{
					return ActionResult.Failure;
				}
			}
		}
		Tuple<HttpStatusCode, string> uploadAppResponse = MakeQrsRequest("/app/upload?name=Telemetry Dashboard", HttpMethod.Post, HTTPContentType.app, Properties.Resources.Telemetry_Dashboard);
		if (uploadAppResponse.Item1 == HttpStatusCode.Created)
		{
			return ActionResult.Success;
		}
	}
	return ActionResult.Failure;
}
```

For me the qualifying question here would be:
1. Do you have an app named `Telemetry Dashboard`?
2. If yes, can you rename it `Telemetry Dashboard-old`?

**Comment by Abhinovqlik** [comment]
@levi-turner  No,  I dont have any Telemetry dashboard installed on my server, Im trying to install. But it rool back . As I mentioned.

**Comment by levi-turner** [comment]
@abhinov04 : Can you import any arbitrary app? It seems as though that is the step which is failing. For example this attached app
[Random Data.qvf.zip](https://github.com/eapowertools/qs-telemetry-dashboard/files/3198509/Random.Data.qvf.zip)

**Comment by levi-turner** [comment]
@Abhinovqlik : Still an issue?

**Comment by NickAkincilar** [comment]
I had the same issue. windows UAC is the issue. There is no option to run the MSI as an administrator using the right click option. What I had to do was run the command prompt CMD.exe as an elevated administrator first. Then type in the MSI path in the command prompt to trigger with elevated privileges.

**Comment by levi-turner** [comment]
@NickAkincilar : You should be able to provide rights to the requisite folder using Windows. Reference: https://youtu.be/EPLl1BODwH4?t=64
