### ISSUE TITLE
Run metadata fetch on (active) central

### ISSUE THREAD

**Issue by jparis** [eapowertools/qs-telemetry-dashboard#7]
External Program Tasks can be executed on slave schedulers which will not have all / any apps load balanced. This reduces the usefulness of the metadata fetch process.

**Comment by rzenere-synthese** [comment]
Hey @jparis , we're running exactly in the issue you mentioned. Is there an estimated ETA for this enhancement?

Many thanks for your work,
Riccardo

**Comment by jparis** [comment]
Not yet no. I imagine it may be sometime next month. If you want to make the change and submit a PR, feel free and I can review/merge it.

**Comment by jparis** [comment]
Done. Will be in v4.2.0 release.
