### ISSUE TITLE
No metadata collected on multi node virtual proxy with prefix

### ISSUE THREAD

**Issue by kghovanlou** [eapowertools/qs-telemetry-dashboard#73]
We have successfully installed and ran the Telemetry dashboard on our dev environment which has no prefix on the virtual proxy.
 
When trying to install and run this on our production environment, which does have a prefix, it will not collate the data correctly.
 
When kicking off the task it 'completes' in less than 30 seconds. The MetadataOutput folder is populated with the 9 csv files, but each file remains empty (apart from headers). The app after reload will show objects and UIDs, but there is no app or sheet names associated to them.
 
Is this a known issue? (couldn't see anything in the wiki or closed issues)

**Comment by levi-turner** [comment]
Somehow missed this, the metadata fetch process doesn't go over the Proxy, so this _shouldn't_ be an issue. Is this still a concern?

**Comment by kghovanlou** [comment]
Hello Levi, it has been resolved after installing your latest version. Thank you.
