### ISSUE TITLE
Error when trying to upgrade to the latest version

### ISSUE THREAD

**Issue by tduarte-ctx** [eapowertools/qs-telemetry-dashboard#74]
I installed the Telemetry Dashboard about a year ago so decided was time for an upgrade.
I tried upgrading on both our Dev and Prod environments and getting errors on both during the upgrade to v4.4.1.
We are running Qlik Sense February 2021 release.

**Prod**
1       2021-11-08T15:31:51.4116486Z    Info    Arguments handled and logging initialized.
2       2021-11-08T15:31:51.8833343Z    Info    Preparing to run initialize mode, this will create two tasks, import an application and create two data connections in your environment, press 'q' to quit or any other key to proceed:
3       2021-11-08T15:31:54.0874433Z    Info    Please enter the 'DOMAIN\user' for the service account running Qlik Sense Enterprise (without quotes, example: QLIK\jparis):
xxxxxxxxxxx\xxxxxxx
4       2021-11-08T15:32:08.2300787Z    Info    The user 'xxxxxxxxxx\xxxxxx' was entered.
5       2021-11-08T15:32:08.2320366Z    Info    Initialize Mode:
6       2021-11-08T15:32:08.2339863Z    Info    Running in initialize mode.

Unhandled Exception: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.Run(String serviceAccount, Boolean skipCopy)
   at qs_telemetry_dashboard.TelemetryDashboardMain.Main(String[] args)

**Dev**
C:\>TelemetryDashboard.exe -initialize
1       2021-11-08T15:29:35.0168898Z    Info    Arguments handled and logging initialized.
2       2021-11-08T15:29:35.4768805Z    Info    Preparing to run initialize mode, this will create two tasks, import an application and create two data connections in your environment, press 'q' to quit or any other key to proceed:
3       2021-11-08T15:29:38.3288773Z    Info    Please enter the 'DOMAIN\user' for the service account running Qlik Sense Enterprise (without quotes, example: QLIK\jparis):
xxxxxxxxxx\xxxxxxxxx
4       2021-11-08T15:29:51.3518744Z    Info    The user 'xxxxxxxxxxx\xxxxxxxx' was entered.
5       2021-11-08T15:29:51.3548809Z    Info    Initialize Mode:
6       2021-11-08T15:29:51.3568798Z    Info    Running in initialize mode.
7       2021-11-08T15:29:52.1618853Z    Info    A single existing App 'TelemetryDashboard' was found.

Unhandled Exception: qs_telemetry_dashboard.Exceptions.InvalidResponseException: OK returned when trying to replace Telemetry Dashboard app. Request failed.
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.ImportApp()
   at qs_telemetry_dashboard.Initialize.InitializeEnvironment.Run(String serviceAccount, Boolean skipCopy)
   at qs_telemetry_dashboard.TelemetryDashboardMain.Main(String[] args)

**Comment by jparis** [comment]
For dev, that seems like a bug i might need to fix. in the meantime you can just rename any apps named 'Telemetry Dashboard' to 'Telemetry Dashboard - old' or something. Weird I'm incorrectly handing a return.

As for the first issue, looks like a permissions issue to the share drive.

**Comment by tduarte-ctx** [comment]
Hi Jesse,
Thanks for the quick reply.

Renaming the app on Dev before running the .exe did the trick.

Now, for Prod, I'm running the .exe with the Qlik Sense service account which already has Full Control access to the server share. I can see the .exe was copied to the TelemetryDashboard folder on the share. How can I troubleshoot this further?

Thanks,
Telmo

**Comment by jparis** [comment]
Yep, so what you can do is call TelemetryDashboard.exe with `-initialize -skipcopy` This will skip the copy step and you won't have those permissions issue since the binary is already in the right spot.

You will need to make sure the account RUNNING the qlik services also have access to the telemetrydashboard.exe. You can change those permissions manually.

**Comment by tduarte-ctx** [comment]
The skip got me to a bit further but also had to rename the existing app first for the import to work.
Thanks.
