### ISSUE TITLE
TelemetryDashboard-1-Generate Metadata task not being created during installation

### ISSUE THREAD

**Issue by vthokala-jef** [eapowertools/qs-telemetry-dashboard#74]
Dear Support,

I've gone through the installation and do see the App, Data connections and the TelemetryDashboard-2-Reload Dashboard task are created but the task TelemetryDashboard-1-Generate Metadata is not.

Could you please help?

Thanks,
Venkata

**Comment by jparis** [comment]
What version of Qlik Sense are you on? Was this the first time you ever tried to install the telemetry dashboard?

**Comment by vthokala-jef** [comment]
We are on Nov-2018 Patch-3. This is the first time we are trying to install telemetry...

**Comment by jparis** [comment]
Are you logged in as a root admin, and making sure you look at all tasks, not just reload tasks? If the second task got created, the first should have as well.

**Comment by vthokala-jef** [comment]
Yes i did login as root admin. I've checked the task list without filter and i dont see the first task.

**Comment by jparis** [comment]
I would suggest uninstalling and reinstalling.

**Comment by vthokala-jef** [comment]
I've done that too but not successful.

**Comment by jparis** [comment]
Yes, absolutely:

You'll have to use the APIs.

POST /qrs/externalprogramtask

Body looks like:
```{
					'path': '..\\ServiceDispatcher\\Node\\node.exe',
					'parameters': '""" + Path.Combine(installDir, JS_LIBRARY_FOLDER) + @"\\fetchMetadata.js""',
					'name': 'TelemetryDashboard-1-Generate-Metadata',
					'taskType': 1,
					'enabled': true,
					'taskSessionTimeout': 1440,
					'maxRetries': 0,
					'impactSecurityAccess': false,
					'schemaPath': 'ExternalProgramTask'
				}```
Where you need to change Path.Combine() to the path to the fetchMetadata.js file.
