### ISSUE TITLE
Unable to Install Telemtry

### ISSUE THREAD

**Issue by prashanthi-g** [eapowertools/qs-telemetry-dashboard#75]
Hi,
 I was trying to install telemetry on the the serevr but because of the convension we followed while installing the Qliksense application(Shared folders are named with a prefix Qliksense likes apps as Qliksense App, Archive logs as QliksenseArchivelogs).

Tellimetry installer is unable to recognized the folders from the Qliksense share folder.

Please let me know whate can be done so that I can install it on my server.

**Comment by jparis** [comment]
I replied to your issue here: https://github.com/eapowertools/qs-telemetry-dashboard/issues/27

Are you still having problems?

**Comment by prashanthi-g** [comment]
Hi Jesse,

Thank you for the response. 
Do I have to make any changes?
I dont see any data from QIX performance logs.

Error when i load from hub:
            Table QIXPerformance_Engine not found for one of the rim node
In qmc ,I set it to info. 
And i do see thePerformance txt file in the location.

**Comment by jparis** [comment]
Have you done all this?

https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Logging
