### ISSUE TITLE
Adding Banner to Qlik Sense to make sure users are using right Environment 

### ISSUE THREAD

**Issue by Abhinovqlik** [eapowertools/qs-telemetry-dashboard#76]
Hello Team,

I am looking for the Banner on qliksense hub, when users login to the Dev or Test Environment wanted to make sure they are using right access to the hub.

can anyone help on this.

**Comment by jparis** [comment]
Not sure I understand what you're asking.

**Comment by levi-turner** [comment]
https://support.qlik.com/articles/000057651 ?

**Comment by Abhinovqlik** [comment]
here is the attachment what I'm looking for.
![3BCBF2E4](https://user-images.githubusercontent.com/50502205/61563082-af1ef980-aa27-11e9-8201-6994fd172b0d.PNG)

**Comment by levi-turner** [comment]
I am not sure where this page is coming from. It's either an already rebranded Forms login page which is hosted by Qlik Sense or it's a third party website used in an integration. In either case, it's not in the scope of this project. Please use [Qlik Community](https://community.qlik.com) for assistance.
