### ISSUE TITLE
this is not an issue, but a workaround on scheduling the external program

### ISSUE THREAD

**Issue by SusanHS** [eapowertools/qs-telemetry-dashboard#76]
Today we found an easier way to schedule the external program, than using the scirpt given in this site.
Steps:
1. create a new external program task and copy path & parameters from the original task
2. schedule it normally
3. link Telemetry Dashboard reload task to the task created in step 1.

My question:
Do you see any potential harm with this method?

Best regards,
Susan

**Comment by levi-turner** [comment]
@SusanHS : No harm. I'm guessing that you're running May 2021 or newer which unlocks the ability to create / edit External Program Tasks natively in the Management Console. Any scripts here were really meant for prior versions where API calls were required.

Cheers
