### ISSUE TITLE
Dashbord sheet has a bug to display max RAM usage graph

### ISSUE THREAD

**Issue by gkrish26** [eapowertools/qs-telemetry-dashboard#77]
Hi,

what i have found in a multi node environment, the refresh of this metadata  takes place on reload node for example (it has 300 GB ram) but the engine nodes/consumer node  have 1 TB ram. the graph values set to 300gb  irrespective of host that you selecting. the phisical ram should be adjusted based on the ram available on the host.

![image](https://user-images.githubusercontent.com/22492893/61796587-f80aef80-ae25-11e9-932a-e2254f61b846.png)

**Comment by levi-turner** [comment]
Yes, this is a known issue at current. It's tracked under: https://github.com/eapowertools/qs-telemetry-dashboard/issues/58 Feel free to follow that thread to get push notified when we release an improvement to resolve it.

Cheers.
