### ISSUE TITLE
do we need to set vActiveAll = 1?

### ISSUE THREAD

**Issue by SusanHS** [eapowertools/qs-telemetry-dashboard#77]
Hei
In Telemetry Dashboard loadscript, there is a variable called vActiveAll. Load script says: 'In load script, it says 'This variable controls whether the Telemetry Dashboard will parse active logs from all nodes'
By default, vActiveAll = 0. With this value, we got also data from all our RIM nodes. 

will I get more data if we enable the vActiveAll? 

Best regards,
Susan

![image](https://user-images.githubusercontent.com/64188274/148737330-05b2a8b8-0136-4218-a497-50002ceda639.png)

**Comment by levi-turner** [comment]
Logs are archived from all nodes every 12 hours / 8MB / service restart ([reference](https://community.qlik.com/t5/Knowledge/How-logging-works-in-Qlik-Sense-Enterprise-on-Windows/ta-p/1715137)).

The Telemetry Dashboard, by default, uses the `ServerLogFolder` and `ArchivedLogFolder` folder paths. This means that, in a multi-node context, that the log data in the Telemetry Dashboard could be up to 12 hours old.

For the vast majority of use cases, this is perfectly sufficient. But there was a customer who needed data with a much lower latency.

In scenarios where lower latency is required, then you can both adjust the `vActiveAll` variable to `1` **and** configure + define folder connections to the active log path (`%ProgramData%\Qlik\Sense\Log`) for all nodes. Example:

```
// -------------------------------------------------------------------------
// This variable controls whether the Telemetry Dashboard will parse active logs from all nodes
// 1 = enabled
// 0 = disabled
// If enabled, configure data connections to C:\ProgramData\Qlik\Sense\Log for all nodes in the environment and specify the data connection names in next section. Example:
// data connection name		|		data connection path	| 	local path
// QLIKSERVER01				| 		\\QLIKSERVER1\Log		| 	C:\ProgramData\Qlik\Sense\Log (on QLIKSERVER01)
// QLIKSERVER02				| 		\\QLIKSERVER2\Log		| 	C:\ProgramData\Qlik\Sense\Log (on QLIKSERVER02)
// QLIKSERVER03				| 		\\QLIKSERVER3\Log		| 	C:\ProgramData\Qlik\Sense\Log (on QLIKSERVER03)
// -------------------------------------------------------------------------
LET vActiveAll = 1;

// Define the data connection names for explicit data connections for all nodes
FolderPathsTable:
LOAD * INLINE [
FolderPaths
lib://MyNode1
lib://MyNode2
lib://MyNode3
];
```

**Comment by SusanHS** [comment]
Thank you Levi! Now I understand 😊
