### ISSUE TITLE
'TelemetryDashboard' is not a valid short file name when installing on a remote share

### ISSUE THREAD

**Issue by RRKONDAVETI** [eapowertools/qs-telemetry-dashboard#78]
hello, We have our QS share on network drive not on Qliksense server, where we should we install telemetry in this scenario?

Cheers,
RK

**Comment by levi-turner** [comment]
@RRKONDAVETI : In the share used by Qlik Sense. It's no different than if the share were hosted on a server which also ran Qlik Sense: https://youtu.be/EPLl1BODwH4?t=130

**Comment by RRKONDAVETI** [comment]
Hi i have tried it but it is throwing error message
![image](https://user-images.githubusercontent.com/40630446/62288282-ef34a200-b453-11e9-91aa-ca05e9cab713.png)

**Comment by RRKONDAVETI** [comment]
qliksense cluster root folder 

![image](https://user-images.githubusercontent.com/40630446/62288381-2acf6c00-b454-11e9-8977-2db4235207fb.png)

**Comment by RRKONDAVETI** [comment]
tried it but throwing error message 
![image](https://user-images.githubusercontent.com/40630446/62288620-b1844900-b454-11e9-8ad3-90aa588e971c.png)

**Comment by levi-turner** [comment]
@jparis : This is the same issue that Eugene and co are having.

Can you try launching the msi from the command prompt with the following command?
`msiexec /i <filenameToMSI> TARGETDIR="C:\"`

If that fails, can you gather the log and send it over? Instructions are here: https://youtu.be/EPLl1BODwH4?t=174

**Comment by RRKONDAVETI** [comment]
Hi Levi, 
you mean to run msiexec /i D:\Qlik\TelemetryDashboard.msi TARGETDIR="\\fileserver\Published$" ?

**Comment by levi-turner** [comment]
No, I mean specify the TARGETDIR as TARGETDIR="C:\". So for you:
`msiexec /i D:\Qlik\TelemetryDashboard.msi TARGETDIR="C:\"`

**Comment by scarstruck4** [comment]
Hi team,
I am experiencing the same issue as Rrkondaveti. what exactly is going wrong?

**Comment by levi-turner** [comment]
Unclear if @RRKONDAVETI has done the step that I mentioned before. Can you give it a shot?

`msiexec /i Drive:\Path\To\TelemetryDashboard.msi TARGETDIR="C:\"`

If that still fails please attach the installation log (https://youtu.be/EPLl1BODwH4?t=174)?

Thanks

**Comment by jparis** [comment]
Can you try running this:

`msiexec /i Drive:\Path\To\TelemetryDashboard.msi TARGETDIR="C:\`

from an admin command prompt?

Pretty sure it's a permissions issue.

**Comment by levi-turner** [comment]
Just ran into this today on an install. The ultimate cause, for me, was that the account executing the MSI did not have Read/Write rights on the Share being used (although they had full control at the NT level).

**Comment by RRKONDAVETI** [comment]
> TARGETDIR="C:\"

I  got a chance to look it at again today. If i run the 
msiexec /i Drive:\Path\To\TelemetryDashboard.msi TARGETDIR="C:\
 doesn't install on C drive on QS sever instated of  remote file share share ?

**Comment by RRKONDAVETI** [comment]
> Just ran into this today on an install. The ultimate cause, for me, was that the account executing the MSI did not have Read/Write rights on the Share being used (although they had full control at the NT level).

I have checked with our admin team the account we are using has got full control and read and write permissions.

**Comment by levi-turner** [comment]
> If i run the `msiexec /i Drive:\Path\To\TelemetryDashboard.msi TARGETDIR="C:\"` doesn't install on C drive on QS sever instated of remote file share share?

No, the goal of that command was to over-ride a variable called in the installer which mistakenly places the `TARGETDIR` to another drive.

**Comment by RRKONDAVETI** [comment]
@levi-turner  
![Capture](https://user-images.githubusercontent.com/40630446/64254188-c69e3d00-cf16-11e9-96a5-acf236dabff0.PNG)

**Comment by levi-turner** [comment]
@RRKONDAVETI : You've not closed the last `"`. The command should be `msiexec /i C:\Qlik\Tools\TelemetryDashboard.msi TARGETDIR="C:\"`.

**Comment by RRKONDAVETI** [comment]
> @RRKONDAVETI : You've not closed the last `"`. The command should be `msiexec /i C:\Qlik\Tools\TelemetryDashboard.msi TARGETDIR="C:\"`.

Sorry.. i did run it again now it is asking for destination folder 
![Capture](https://user-images.githubusercontent.com/40630446/64264523-5947d780-cf29-11e9-907c-d3adecd91323.PNG)

**Comment by levi-turner** [comment]
OK, so set that to your share path. For example my share for my local site is `\\Levi-PC\Share` so I'd set it to `\\Levi-PC\Share\TelemetryDashboard`

**Comment by RRKONDAVETI** [comment]
@levi-turner , Looks like its permissions issue. our infrastructure guy did install it without any issues. 

Thanks for you help.

**Comment by levi-turner** [comment]
Perfect!
