### ISSUE TITLE
Hard-coded to UTC-7 / PDT

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#8]
The QS app takes 7 hours off the Timestamp field when it extracts data so the times are misleading for those not in UTC-7 / PDT... `Timestamp([Timestamp]-Time#(7,'hh')) as Timestamp,`

Could there be a solution using `ConvertToLocalTime`?

**Comment by jparis** [comment]
My bad. Will fix in next release.

**Comment by jparis** [comment]
Fixed in 1.0.1 release. Worth upgrading to 1.0.2 though for other fixes.
