### ISSUE TITLE
Download link not valid

### ISSUE THREAD

**Issue by tonikautto** [eapowertools/qs-telemetry-dashboard#8]
"Download Latest Here" link on https://github.com/eapowertools/qs-telemetry-dashboard does not lead to a installer.

**Comment by levi-turner** [comment]
@tonikautto : Stay tuned. This project is shifting over to a new delivery + app. @jparis

**Comment by jparis** [comment]
The old telemetry dashboard project has been deprecated, and there is an entirely new .exe available soon as Levi mentioned. If you still want to use the old one, you can find it here: https://github.com/eapowertools-archive/qs-telemetry-dashboard-node

but I would seriously recommend holding off and wait for the new one to drop.
