### ISSUE TITLE
Failed to connect to Qlik Sense Repository Service

### ISSUE THREAD

**Issue by SrinivasaMutha245** [eapowertools/qs-telemetry-dashboard#84]
while installing the Telemetrydashboard in multinode env, I am getting the below error.

1	2022-09-19T13:12:40.5292353Z	Info	Arguments handled and logging initialized.
2	2022-09-19T13:12:40.9361074Z	Error	Repository responded with 'InternalServerError'. Body was: One or more errors occurred.
3	2022-09-19T13:12:40.9361074Z	Error	Failed to connect to Qlik Sense Repository Service. Either it is not running, or the telemetry dashboard cannot reach it.

I am running in the Central node.
Repository Service also running fine.

We have Repo Server as seperate node.

Please let me know how to resolve the issue.

**Comment by jparis** [comment]
What do you mean "we have the repo server as a seperate node"? If you are running on the central node then you should have the repository service running on 4242. Can you confirm using netstat the QRS is indeed running on this port? Or could this have possibly been changed?

**Comment by SrinivasaMutha245** [comment]
Thank you for your Quick reply.

We have total 9 nodes. Out of 9, one node we are using as Qlik Repository Server where we are using to store qvd & QVFs. 

I will confirm on the QRS things also in sometime.

**Comment by SrinivasaMutha245** [comment]
4242 is not being used for QRS. We are seeing 4432 port for QRS.

**Comment by jparis** [comment]
I'm talking about the qlik sense repository service, not the database. The database used 4432.

**Comment by SrinivasaMutha245** [comment]
Hi, 

I am able to see port 4242, but am not able to understand which service is using that port.

**Comment by SrinivasaMutha245** [comment]
hi,

sorry for the delay in replying. QSR service is running. PFA .

![image](https://user-images.githubusercontent.com/113907845/191456770-9640d312-7f56-4832-ac57-8f00cac3ec2b.png)

**Comment by SrinivasaMutha245** [comment]
We have 9 nodes,

1) Central
2) Proxy
3) RIM1
4) RIM2
5) RIM3
6) Scheuler1
7) Scheuler2
8) Scheuler3
9) Repository node where stores all QVF and QVD file.

Do we need to do any configuration setting change?

**Comment by SrinivasaMutha245** [comment]
Hi All, 

I copied and pasted host.cfg and local certificates in my Repository Server node and tried installed the telemetry dashboard.exe. It as installed. 

here is one challenge, in log i am able to see TelemetryDashboard-1-Generate-Metadata task got created but i am not able to see the task in QMC. I am pasting the QMC screenshot also. Only Second task got created which is reload task.

Below is the logs: 
--------------------------------
| Telemetry Dashboard log file |
| v4.4.1                       |
| 2022-09-21T10:25:32.7850593Z |
--------------------------------
C:\Users\PAMAPP-QLIKSENSE\Desktop\log.txt

1	2022-09-21T10:25:32.7860558Z	Info	Arguments handled and logging initialized.
2	2022-09-21T10:25:48.3074635Z	Info	Preparing to run initialize mode, this will create two tasks, import an application and create two data connections in your environment, press 'q' to quit or any other key to proceed:
3	2022-09-21T10:25:55.8396643Z	Info	Please enter the 'DOMAIN\user' for the service account running Qlik Sense Enterprise (without quotes, example: QLIK\jparis): 
4	2022-09-21T10:26:58.7862719Z	Info	The user 'vsnl\svc_qssvc' was entered.
5	2022-09-21T10:26:58.7882756Z	Info	Initialize Mode:
6	2022-09-21T10:26:58.7902761Z	Info	Running in initialize mode.
7	2022-09-21T10:27:15.7174057Z	Info	App 'TelemetryDashboard' was successfully imported.
8	2022-09-21T10:27:15.7333980Z	Info	Existing Data Connection 'TelemetryMetadata' was not found.
9	2022-09-21T10:27:15.7624153Z	Info	Data Connection 'TelemetryMetadata' was created.
10	2022-09-21T10:27:15.7794021Z	Info	Existing Data Connection 'EngineSettingsFolder' already exists.
11	2022-09-21T10:27:15.8224054Z	Info	Existing 'TelemetryDashboard-1-Generate-Metadata' was found.
12	2022-09-21T10:27:15.8514179Z	Info	Deleting existing 'TelemetryDashboard-1-Generate-Metadata' with ID: 0e5382a2-f192-4777-b8db-1db4bed5e56e
13	2022-09-21T10:27:15.9214063Z	Info	Now 'TelemetryDashboard-1-Generate-Metadata' task will be created.
14	2022-09-21T10:27:15.9534051Z	Info	Task 'TelemetryDashboard-1-Generate-Metadata' was created.
15	2022-09-21T10:27:15.9674042Z	Info	No 'TelemetryDashboard-2-Reload-Dashboard' was found. Creating new task.
16	2022-09-21T10:27:16.0114065Z	Info	Task 'TelemetryDashboard-2-Reload-Dashboard' was created.

PFA - QMC Screenshot
![image](https://user-images.githubusercontent.com/113907845/191482869-b2acb0f7-915f-4a0f-881c-fcf891a74758.png)

**Comment by SrinivasaMutha245** [comment]
Hi,

Generatemetadata task was created and able to load the data. it is showing 3 days work of data.
