### ISSUE TITLE
Telemetry App doesn't see some QS Apps

### ISSUE THREAD

**Issue by Justformoment** [eapowertools/qs-telemetry-dashboard#85]
Hi Qlik Team,

I'm facing issue with problem not seeing some application in QS. When I created application for testing and created some diagrams, and went to Telemetry Dashboard Application, in order to see how it performs, but I couldn't find application that I created for testing. Then, I ran fetchMetadata.js in CMD, opened visualizations.csv file, to make sure does Telemetry Dashboard see my app. On this file, I was searching for App ID, then I thought object ID, unfortunately I couldn't find any of them. Then I published app to everyone, it didn't help. Please, could you give some solutions? BTW, could you explain more 2 Telemetry Tasks? Thank you in advance
![Capture](https://user-images.githubusercontent.com/26446355/68393706-daf7f380-016c-11ea-9832-f860b1703f9c.PNG)

**Comment by jparis** [comment]
You won't find the AppID in that table. You can try searching the sheet ID, and it should appear in there.

**Comment by Justformoment** [comment]
Ok, but anyway there is no name of that application in Telemetry Dashboard, I can't see how it performed

**Comment by jparis** [comment]
Open the apps csv file, to see if the app was found. The sheets csv file should map sheets to apps, and the visualizations csv file should map objects to sheets.

**Comment by Justformoment** [comment]
Yeah, I checked all 3 csv files. everything is there. But my app doesn't appear in Telemetry app

**Comment by jparis** [comment]
So if the metadata is indeed in the metadata files, then a reload of the application should show traces of the app, if the app has indeed been used, and QIX logging is enabled. Are you on a multinode environment?

**Comment by levi-turner** [comment]
@Justformoment : But others do? We're looking at the **Details** sheet, yes? That suggests that no interaction with the app that you're interested in breached the thresholds configured for Telemetry logging. Do we have reason to believe that the app would have breached the thresholds?

**Comment by Justformoment** [comment]
@jparis I'm on multinode environment
@levi-turner Telemetry shows not all of apps, it does some of them. Yes, I'm looking at the Details sheet. Is there any log file, that I would say it would be as a condition in one of the *.js files?

**Comment by jparis** [comment]
Note that the reload of the application (second task), pulls the archived logs from all nodes, and the latest logs only from the node it's reloaded on. So if it's reloaded on an engine that you're not accessing said app from, you need to wait for the logs to roll, then reload the telemetry dashboard.

**Comment by levi-turner** [comment]
@Justformoment : So let's take a step back. What are your Telemetry settings in the `Settings.ini`? Those define a threshold (time based and/or memory based). **If** an application's request breaches this threshold, then a line will be written to the Engine's QIX Performance logs. So to verify you can search the QIX Performance logs (both in the active log location as well as the archived path) for the app's ID.

**Comment by Justformoment** [comment]
Hi guys, now I got you. Ok, my application is listed in telemetry dashboard. The 2nd question is that in what cases Telemetry will show me information about me app? There is one sheet in my app, but I don't see any records(process time, peak RAM and so on) of it in Telemetry

**Comment by levi-turner** [comment]
> The 2nd question is that in what cases Telemetry will show me information about me app?

When any call to the Engine (i.e. requesting a visualization, a sheet, etc) breaches the thresholds that you have configured. Let's look at the example `Settings.ini` entry:

```
[Settings 7]
ErrorPeakMemory=2147483648
WarningPeakMemory=1073741824
ErrorProcessTimeMs=60000
WarningProcessTimeMs=30000
```

If any request to the Engine takes over 1GB (`WarningPeakMemory`) or takes over 30 seconds (`WarningProcessTimeMs`) then the Engine will log the request as a warning. If any request to the Engine takes over 2GB (`ErrorPeakMemory`) or takes over 60 seconds (`ErrorProcessTimeMs`) then the Engine will log the request as an error. These warnings or errors are logged to the Telemetry _logs_ which are then consumed by the Telemetry Dashboard.

**Comment by Justformoment** [comment]
I got you. Please, could you explain me more detailed what 2 Telemetry Tasks do?
Moreover, I would like to know, what is frequency of generation of metadata, and can we change it?

**Comment by levi-turner** [comment]
* `TelemetryDashboard-1-Generate-Metadata`: This task kicks off a series of NodeJS scripts which make Engine API calls. This refreshes the meta-data which provides the insight into which sheet a given object is in.

Think this field:
![image](https://user-images.githubusercontent.com/23237561/68869095-a0d7a600-06c6-11ea-9537-b3831bbab4a0.png)

It also unlocks what _type_ of visualization an object is. So this:
![image](https://user-images.githubusercontent.com/23237561/68869150-b4830c80-06c6-11ea-8828-baee211418f1.png)
 
* `TelemetryDashboard-2-Reload-Dashboard`: This reloads the actual Qlik app which feeds from the QIX Performance Logs + the metadata generated by the first task.

As far as scheduling the first task, see: https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata

**Comment by Justformoment** [comment]
Thank you guys, you're doing good job.
