### ISSUE TITLE
Question: Can we improve the log event to dashboard latency? 

### ISSUE THREAD

**Issue by steveonabike** [eapowertools/qs-telemetry-dashboard#86]
We love this dashboard. We would like to improve the lag between when an event is logged and when it appears in the dashboard after a reload. If we have an event and reload the app soon(1hr) after the event, it does not appear in the dashboard sometimes until the next daily reload.

**Comment by jparis** [comment]
The issue with the lag, I'm guessing in your environment, is a multi-node scenario.

Basically, the engine that reloads the app pull all the archived logs, but the most recent logs ON that engine. My guess is the most recent logs on the engine you are using for consumption are still on THAT engine, and haven't rolled into the archived logs folder yet. Logs roll into the archived log folder I believe either: daily, when they hit 8mb, or when the services are restarted.

There's no good way to get up to date information from all engines unless you were to build some system that pull all the local logs from each engine as well as the archived logs.

**Comment by steveonabike** [comment]
@jparis As you've described. We are running multi-node with dedicated reload nodes. You've got me thinking about how I could reload only this app on the consumption nodes, so that I could get the most recent app log data.

**Comment by levi-turner** [comment]
@steveonabike : If you are using a recent release of the Telemetry Dashboard then you can configure it to include the active logs in the reload. See https://youtu.be/iLKOpnKbLJg for guidance.

**Comment by steveonabike** [comment]
Thanks for adding that functionality to the latest release and for the helpful config video. Works great!
