### ISSUE TITLE
Central node Log folder path

### ISSUE THREAD

**Issue by Justformoment** [eapowertools/qs-telemetry-dashboard#89]
Hello guys,
I work on multi node environment. I have question regarding central node. If I understand ServerLogFolder path points to central node log folder. So, should I add this path into FolderPathsTable?
Like this:

FolderPathsTable:
LOAD * INLINE [
FolderPaths
lib://ServerLogFolder
];

Thank you in advance

**Comment by levi-turner** [comment]
Out of the box, this is already handled. The reason why you'd want to use that section is if you wanted to ensure that you included up-to-date logs on RIM nodes. Reference: https://youtu.be/iLKOpnKbLJg

**Comment by Justformoment** [comment]
So, it means that I don't have to specify any log path of other nodes there, even central one, right?

**Comment by levi-turner** [comment]
Out of the box, the application should work. It will parse the two folder log directories which come with Qlik Sense Enterprise: `ServerLogFolder` (default: `C:\ProgramData\Qlik\Sense\Log`) and `ArchivedLogFolder` (`\\server\share\ArchivedLogs`). This works well for most use cases. This means the application will have logs which are *at least* 12 hours old ([reference](https://support.qlik.com/articles/000031778)). The alternative configuration outlined in that video allows for a more up-to-date application if desired.

**Comment by Justformoment** [comment]
I got you. Can we use logging Database(Postgre) instead?

**Comment by levi-turner** [comment]
Theoretically? Sure. The data should make its way into the QLogs database. Is there direct support in the app at present? No. You can certainly log an improvement here and it'll be addresses based on demand from others.
