### ISSUE TITLE
ArchivedLog connections assumes folder name matches Computername()

### ISSUE THREAD

**Issue by alexometis** [eapowertools/qs-telemetry-dashboard#9]
In our environment our servers were set up with the full name - computername.domain.internal. This is used in the sub-folders in the archived log directories amongst other places.

The Telemetry dashboard only looks for a folder in there that matches the `ComputerName()` function in Qlik Sense which just returns the first part - computername in the example above.

Not sure of the fix - perhaps load all subfolders in the ArchivedLogs folder or any that match ComputerName*? As a workaround, I've just appended the domain name on the end of the variable in the script.

**Comment by jparis** [comment]
That's what qlik resolves as the computer name, and no way to pull the FQDN. Best way to fix this is to just add the domain to the variable set on line ~20 (ish). Would rather have an explicit match and not against a wildcard domain.

Will document though.

**Comment by jparis** [comment]
Added note in documentation. Closing.
