### ISSUE TITLE
Telemetry dashboard does not show Reload and ReloadEx methods

### ISSUE THREAD

**Issue by hammamr** [eapowertools/qs-telemetry-dashboard#90]
Hello,

I have an issue with telemetry dashboard, it does not show the prcess Time and RAM pic for reloads (see the attatched print screen), is it normal ?

Also i have a question on the metric ProcessTime, what does it mean? is it the real time spent by the engine to process the operation? or the pic of CPU time used by the operation on the engine?

I need the pic of % used CPU by the application or a visualization, is it possible to get this metric in the telemetry dashboard?

Best Regards.
Sidi
![Methods_Shown_by_telemetry_dashboard](https://user-images.githubusercontent.com/41787890/70443541-9ecfef80-1a98-11ea-81d4-2dd1a35aebac.PNG)

**Comment by levi-turner** [comment]
> reloads

Perhaps. There may've been a version released which explicitly excluded Reloads. To confirm, check the *Telemetry Root* & *Telemetry Archives* sections of the load script for the app. Inside those sections, ensure that `Method<>'Doc::DoReload` and `Method<>'Doc::DoReloadEx'` are not filtered.
Example load scripts:
*Telemetry Root*:
```
sub DoDirLESTXT (Root)
	for each Ext in '*.txt'
		for each File in filelist (Root&'\*Qix*' &Ext)
            Concatenate (QIXPerformance_Engine)
            LOAD 
                Timestamp(ConvertToLocalTime([Timestamp])) as Timestamp,
                Date(Floor([Timestamp])) as Date, 
                HOUR(ConvertToLocalTime([Timestamp])) as HourNbr,
                [Level],
                [Hostname],
                [Id],
                //[ProxySessionId],
                [ActiveUserDirectory],
                [ActiveUserId],
                [CServerId] as SessionId,
                IF([Method]='<Unknown>','OpenApp Call',[Method]) as [Method],
                IF(Method='GenericObject::GetLayout', 'Visualization Objects Only', 
                	IF(Method='Global::OpenApp', 'OpenApp Only', 
                	IF(Method like 'Doc::DoReload*', 'Reloads Only'))) as [Request Filter],
                [ProcessTime],
                round(ProcessTime/1000) as [Process Time (s)],
                //[TraverseTime],
                [DocId] AS [AppID-DocId],
                IF([ObjectId]='<Unknown>','N/A',[ObjectId]) AS [ObjectId-VisualizationID],
                [NetRAM],
                [PeakRAM],
                IF([ObjectType]='<Unknown>','N/A',[ObjectType]) AS [ObjectType]
            FROM
            '$(File)'  (txt, utf8, embedded labels, delimiter is '\t', msq)
                	WHERE //Method<>'Doc::DoReload'  	//removes reloads from data
			 		//AND Method<>'Doc::DoReloadEx'			//removes reloads from data
                    Method<>'Global::GetInteract'	//removed tracing from hub reloads
                    AND Method<>'Global::InteractDone'	//removed tracing from hub reloads
                    AND Method<>'Global::GetProgress';	//removed tracing from hub reloads   
		next File
	next Ext
	for each Dir in dirlist (Root&'\Log\Engine\*' )
		call DoDirLESTXT (Dir)
	next Dir
end sub


IF $(vActiveAll) = 1 then 
	//******************************************************
	// Load QIX Performance (Telemetry) from the active log folder on all nodes
	//******************************************************
	FOR vRow=1 to NoOfRows('FolderPathsTable')
	LET vFolderPath  = Peek('FolderPaths' , vRow-1, 'FolderPathsTable');
		call DoDirLESTXT ('$(vFolderPath)\Engine\Trace');
	NEXT vRow;
Else 
	//******************************************************
	// Load QIX Performance (Telemetry) from the ServerLogFolder directory
	//******************************************************
	call DoDirLESTXT ('$(vLogRoot)\Engine\Trace');
	End If
```

*Telemetry Archives*:
```
//******************************************************
// Load QIX Performance (Telemetry) from the ArchivedLogFolder directory (all nodes)
//******************************************************

//Set vConcatenate = ;
sub ScanFolder(Root)
	for each FileExtension in 'log'
		for each FoundFile in filelist( Root & '\*QixPerformance*' & FileExtension)
			IF round(num(date(today())-date(FileTime('$(FoundFile)')))) <= '$(v#LogDays)' then
                Concatenate (QIXPerformance_Engine) 
                LOAD
                    Timestamp(ConvertToLocalTime([Timestamp])) as Timestamp,
                    Date(Floor([Timestamp])) as Date, 
                    HOUR(ConvertToLocalTime([Timestamp])) as HourNbr,
                    [Level],
                    [Hostname],
                    [Id],
                    [ProxySessionId],
                    [ActiveUserDirectory],
                    [ActiveUserId],
                    [CServerId] as SessionId,
                    [Method],
                    IF(Method='GenericObject::GetLayout', 'Visualization Objects Only', 
                    	IF(Method='Global::OpenApp', 'OpenApp Only', 
                        IF(Method like 'Doc::DoReload*', 'Reloads Only'))) as [Request Filter],
                    [ProcessTime],
                    round(ProcessTime/1000) as [Process Time (s)],
                    //[TraverseTime],
                    [DocId] AS [AppID-DocId],
                    IF([ObjectId]='<Unknown>','N/A',[ObjectId]) AS [ObjectId-VisualizationID],
                    [NetRAM],
                    [PeakRAM],
                    IF([ObjectType]='<Unknown>','N/A',[ObjectType]) AS [ObjectType]
                FROM [$(FoundFile)] (txt, utf8, embedded labels, delimiter is '\t', msq)
                	WHERE //Method<>'Doc::DoReload'  	//removes reloads from data
			 		//AND Method<>'Doc::DoReloadEx'			//removes reloads from data
                    Method<>'Global::GetInteract'	//removed tracing from hub reloads
                    AND Method<>'Global::InteractDone'	//removed tracing from hub reloads
                    AND Method<>'Global::GetProgress';	//removed tracing from hub reloads   
			End If
		next FoundFile
	next FileExtension
          for each SubDirectory in dirlist( Root & '\*' )
                    call ScanFolder(SubDirectory)
          next SubDirectory
end sub
Call ScanFolder('$(vLogArchive)') ;
```

**Comment by levi-turner** [comment]
> %

No. Percentages are not recorded in the underlying logs and there's no obvious use case for trying to translate a duration (# of milliseconds) should be converted to a percentage.

**Comment by hammamr** [comment]
Effectively, there is a filter in the two sections Telemetry Root & Telemetry Archives sections of the load script ti exclude Reloads.

What is the reason behind to exclude the reloads from the dashboard?

I was wandering if we can give different peakTimeProcess and PeakRam for reloads?

What does mean the ProcessTime in the dashbord? is it the real time or CPU time?

Best regards.

**Comment by levi-turner** [comment]
> What is the reason behind to exclude the reloads from the dashboard?

It seemed too noisy for the releases. Based on feedback this behavior has changed in the master copy of the app so future releases will add them back in.

> I was wandering if we can give different peakTimeProcess and PeakRam for reloads?

Meaning you'd want those metrics _only_ for reloads? In all honesty the distinction between `NetRAM` and `PeakRAM` is fairly nuanced so the decision was made to focus on the `Net` metrics (RAM and Process time).

> What does mean the ProcessTime in the dashboard? is it the real time or CPU time?

I am not seeing the distinction. What is recorded in the QIX Performance logs is the time in between the user submitted a request (do a reload, display a bar chart, open an app) and when the Engine successfully delivers that request. This can be thought of as the time the user spent waiting (plus the time it takes for the network to communicate the data). At a high level a request to the Engine can be broken into these steps:

1. User's browser makes a request
2. The request is sent over a network or series of networks to the server
3. The server receives the request and begins processing it
4. The server finalizes the computation that is needed for the request
5. The request is sent back over a network or series of networks to the user's browser
6. The client side code is activated to render the result

Telemetry covers 3-4.

Is that what you're asking? Whether this is the time the user spent waiting? If so, then it's an approximation. The Qlik server does not have a mechanism to measure the latency / throughput between the server and the client, so it cannot record or estimate the time it takes for a
