### ISSUE TITLE
telemetry dash board refresh fails due to Drop Table node_list not found 

### ISSUE THREAD

**Issue by gkrish26** [eapowertools/qs-telemetry-dashboard#91]
Hi,

can you please let us know the reason for failure and how to fix the issue ? when i comment the line the dashboard refreshes but not sure that makes any difference. 

WHERE "@1:n" LIKE 'ErrorPeakMemory*'
2020-02-25 09:49:16      	1 fields found: ErrorPeakMemory, 
2020-02-25 09:49:16      4 lines fetched
2020-02-25 09:49:16 0619 Drop Table node_list
2020-02-25 09:49:16      Error: Table not found
2020-02-25 09:49:16      Execution Failed
2020-02-25 09:49:16      Execution finished.

**Comment by levi-turner** [comment]
What version of the app are you running (Script > Variables & Config section > `vTelemetryVersion`)?

Generically the source of that table is found in the `MultiNode Config` section of the load script. This section is calling `vLogArchive` to enumerate the nodes found in that folder. That variable in turn is defined in the `Variables & Config` section (`Let vLogArchive = 'lib://ArchivedLogsFolder'`). Assuming you have not adjusted this data connection, can you post a screenshot of that data connection. Like so:
![image](https://user-images.githubusercontent.com/23237561/75239058-017b8200-5790-11ea-8021-050a3c5dc8a6.png)

**Comment by gkrish26** [comment]
Hi Turner,
Thanks for the info. issue been resolved after changing the connection.
