### ISSUE TITLE
finding threshold values

### ISSUE THREAD

**Issue by arjunaraoj** [eapowertools/qs-telemetry-dashboard#93]
Hi All,

We are facing "Engine is unavailable" issue when we reloading 2 apps each size is with 13 GB .

We want to Set Threshold Parameters for Settings.ini file in the Qliksense server file.
Our motive is to configure Telemetry Dashboard.
Please help us to how find the below values for my Qlik Environment?

Windows RAM is 96 GB.

[Settings 7]
ErrorPeakMemory=2147483648
WarningPeakMemory=1073741824
ErrorProcessTimeMs=60000
WarningProcessTimeMs=30000

**Comment by levi-turner** [comment]
I am not sure what is being asked. Are you asking what are the appropriate values? From [our wiki](https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Logging#set-threshold-parameters), you're going to want to open up the Engine's Settings.ini file (`C:\ProgramData\Qlik\Sense\Engine\Settings.ini`) and add in the ErrorPeakMemory, WarningPeakMemory, ErrorProcessTimeMs, WarningProcessTimeMs keys with their values. Reference [this Qlik Support article](https://support.qlik.com/articles/000025502) on how to modify the Settings.in if you're unfamiliar.

**Comment by arjunaraoj** [comment]
Dear @levi-turner , I have gone through this. But did not understand what values I need to keep inside the settings.ini file. Thank you so much for your help. My UAT server RAM size is 96 GB.

**Comment by levi-turner** [comment]
The values that you posted before are fine for almost all deployments. It's high enough to focus only on the significantly heavy applications and has enough of a delta between the `error` and `warn` levels to see growth over time.

**Comment by arjunaraoj** [comment]
Thank you Levi-turner. I have used real values as mentioned below.

 [Settings 7]
ErrorPeakMemory=70073741824 (70 GB)
WarningPeakMemory=25147483648 (25 GB)
ErrorProcessTimeMs=300000 (300 sec)
WarningProcessTimeMs=144000 (144 sec)

Please advise, is this wrong?
Thanks in advance.

**Comment by levi-turner** [comment]
Insofar as the file looks like this:

```
[Settings 7]
ErrorPeakMemory=70073741824
WarningPeakMemory=25147483648
ErrorProcessTimeMs=300000
WarningProcessTimeMs=144000
```

And not like this:
```
[Settings 7]
ErrorPeakMemory=70073741824 (70 GB)
WarningPeakMemory=25147483648 (25 GB)
ErrorProcessTimeMs=300000 (300 sec)
WarningProcessTimeMs=144000 (144 sec)
```

Then it looks fine. I am not sure how the Engine handles `70073741824 (70 GB)` vs. `70073741824`

**Comment by arjunaraoj** [comment]
> Insofar as the file looks like this:
> 
> ```
> [Settings 7]
> ErrorPeakMemory=70073741824
> WarningPeakMemory=25147483648
> ErrorProcessTimeMs=300000
> WarningProcessTimeMs=144000
> ```
> 
> And not like this:
> 
> ```
> [Settings 7]
> ErrorPeakMemory=70073741824 (70 GB)
> WarningPeakMemory=25147483648 (25 GB)
> ErrorProcessTimeMs=300000 (300 sec)
> WarningProcessTimeMs=144000 (144 sec)
> ```
> 
> Then it looks fine. I am not sure how the Engine handles `70073741824 (70 GB)` vs. `70073741824`

**Comment by arjunaraoj** [comment]
Hi @levi-turner ,I have used parameters without (GBs) as shown below:

[Settings 7]
ErrorPeakMemory=70073741824
WarningPeakMemory=25147483648
ErrorProcessTimeMs=300000
WarningProcessTimeMs=144000


We have two apps App1 and App2 and need to run parallel.
App1 will take 1.2 hr to reload and App2 will take 1.4 hr to reload.
As per QMC logs, App1 and App2 are reloading successfully but not saved the reloaded Apps.
Engine logs say "Engine is Unavailable".
Analysis of % RAM Committed is showing 94%.,Max Engine RAM (GB) is 90.24

The documentation says- ProcessTime: The end-to-end clock time for a request including internal engine operations to return the result.

In this scenario, how to calculate ProcessTime for WarningProcessTime,ErrorProcessTime?
Is this duration between ReloadStartTime & ReloadEndTime or something else?

Thanks in advance.

**Comment by levi-turner** [comment]
@arjunaraoj : I am really not following here. Telemetry logging does not change what resources are needed by Qlik apps (be it app reloads or app consumption). The configs that you have specify
> IF an app uses over 70GB for any operation, THEN log it as an ERROR
> IF an app uses over 25GB for any operation, THEN log it as a WARN
> IF an app takes over 300 seconds to complete any operation, THEN log it as an ERROR
> IF an app takes over 144 seconds to complete any operation THEN log it as a WARN

That's it.

Back to the original goal that you have:
> We are facing "Engine is unavailable" issue when we reloading 2 apps each size is with 13 GB .

The Telemetry Dashboard and associated logging is not going to fix the Engine being unavailable. The design and use case can be adapted to help aid determining _what_ requests are being made which are saturating the server. But in this case, it sounds like you know what two apps are causing problems, yes? If so, then Telemetry will do nothing for you.

So what are we trying to solve for here?

**Comment by arjunaraoj** [comment]
Thank you @levi-turner 
I have managed to find threshold parameters fro my Qliksite.
