### ISSUE TITLE
Do we need to reload TelemetryDashboard-1-Generate-Meta data daily

### ISSUE THREAD

**Issue by arjunaraoj** [eapowertools/qs-telemetry-dashboard#98]
Hi All,
I have successfully configured the Telemetry dashboard successfully.

To get the latest information from Telemetry daily, do I need to run both 1) TelemetryDashboard-1-Generate-Metadata and 2) TelemetryDashboard-2-Reload-Dashboard ?
or Need to create new task for TelemetryDashboard?

Please advise.

**Comment by jparis** [comment]
If you want latest version and the apps are NOT changing, then just the 2nd task. The first task fetches the app metadata.
